
/* !!! This is code generated by Prisma. Do not edit directly. !!! */
/* eslint-disable */
// biome-ignore-all lint: generated file
// @ts-nocheck 
/*
 * This file should be your main import to use Prisma-related types and utilities in a browser. 
 * Use it to get access to models, enums, and input types.
 * 
 * This file does not contain a `PrismaClient` class, nor several other helpers that are intended as server-side only.
 * See `client.ts` for the standard, server-side entry point.
 *
 * 🟢 You can import this file directly.
 */

import * as Prisma from './internal/prismaNamespaceBrowser'
export { Prisma }
export * as $Enums from './enums'
export * from './enums';
/**
 * Model User
 * 
 */
export type User = Prisma.UserModel
/**
 * Model Session
 * 
 */
export type Session = Prisma.SessionModel
/**
 * Model Account
 * 
 */
export type Account = Prisma.AccountModel
/**
 * Model Verification
 * 
 */
export type Verification = Prisma.VerificationModel
/**
 * Model Tenant
 * 
 */
export type Tenant = Prisma.TenantModel
/**
 * Model TenantMember
 * 
 */
export type TenantMember = Prisma.TenantMemberModel
/**
 * Model TenantInvitation
 * 
 */
export type TenantInvitation = Prisma.TenantInvitationModel
/**
 * Model SubscriptionPlan
 * 
 */
export type SubscriptionPlan = Prisma.SubscriptionPlanModel
/**
 * Model Subscription
 * 
 */
export type Subscription = Prisma.SubscriptionModel
/**
 * Model SubscriptionHistory
 * 
 */
export type SubscriptionHistory = Prisma.SubscriptionHistoryModel
/**
 * Model Invoice
 * 
 */
export type Invoice = Prisma.InvoiceModel
/**
 * Model AcademicClass
 * 
 */
export type AcademicClass = Prisma.AcademicClassModel
/**
 * Model AcademicSubject
 * 
 */
export type AcademicSubject = Prisma.AcademicSubjectModel
/**
 * Model AcademicChapter
 * 
 */
export type AcademicChapter = Prisma.AcademicChapterModel
/**
 * Model AcademicTopic
 * 
 */
export type AcademicTopic = Prisma.AcademicTopicModel
/**
 * Model AcademicSubTopic
 * 
 */
export type AcademicSubTopic = Prisma.AcademicSubTopicModel
/**
 * Model Mcq
 * 
 */
export type Mcq = Prisma.McqModel
/**
 * Model Cq
 * 
 */
export type Cq = Prisma.CqModel
/**
 * Model AuditLog
 * 
 */
export type AuditLog = Prisma.AuditLogModel
/**
 * Model SystemSetting
 * 
 */
export type SystemSetting = Prisma.SystemSettingModel
/**
 * Model Notification
 * 
 */
export type Notification = Prisma.NotificationModel
