
/* !!! This is code generated by Prisma. Do not edit directly. !!! */
/* eslint-disable */
// biome-ignore-all lint: generated file
// @ts-nocheck 
/*
 * This is a barrel export file for all models and their related types.
 *
 * 🟢 You can import this file directly.
 */
export type * from './models/User'
export type * from './models/Session'
export type * from './models/Account'
export type * from './models/Verification'
export type * from './models/Tenant'
export type * from './models/TenantMember'
export type * from './models/TenantInvitation'
export type * from './models/SubscriptionPlan'
export type * from './models/Subscription'
export type * from './models/SubscriptionHistory'
export type * from './models/Invoice'
export type * from './models/AcademicClass'
export type * from './models/AcademicSubject'
export type * from './models/AcademicChapter'
export type * from './models/AcademicTopic'
export type * from './models/AcademicSubTopic'
export type * from './models/Mcq'
export type * from './models/Cq'
export type * from './models/AuditLog'
export type * from './models/SystemSetting'
export type * from './models/Notification'
export type * from './commonInputTypes'