
/* !!! This is code generated by Prisma. Do not edit directly. !!! */
/* eslint-disable */
// biome-ignore-all lint: generated file
// @ts-nocheck 
/*
 * WARNING: This is an internal file that is subject to change!
 *
 * 🛑 Under no circumstances should you import this file directly! 🛑
 *
 * All exports from this file are wrapped under a `Prisma` namespace object in the browser.ts file.
 * While this enables partial backward compatibility, it is not part of the stable public API.
 *
 * If you are looking for your Models, Enums, and Input Types, please import them from the respective
 * model files in the `model` directory!
 */

import * as runtime from "@prisma/client/runtime/index-browser"

export type * from '../models'
export type * from './prismaNamespace'

export const Decimal = runtime.Decimal


export const NullTypes = {
  DbNull: runtime.NullTypes.DbNull as (new (secret: never) => typeof runtime.DbNull),
  JsonNull: runtime.NullTypes.JsonNull as (new (secret: never) => typeof runtime.JsonNull),
  AnyNull: runtime.NullTypes.AnyNull as (new (secret: never) => typeof runtime.AnyNull),
}
/**
 * Helper for filtering JSON entries that have `null` on the database (empty on the db)
 *
 * @see https://www.prisma.io/docs/concepts/components/prisma-client/working-with-fields/working-with-json-fields#filtering-on-a-json-field
 */
export const DbNull = runtime.DbNull

/**
 * Helper for filtering JSON entries that have JSON `null` values (not empty on the db)
 *
 * @see https://www.prisma.io/docs/concepts/components/prisma-client/working-with-fields/working-with-json-fields#filtering-on-a-json-field
 */
export const JsonNull = runtime.JsonNull

/**
 * Helper for filtering JSON entries that are `Prisma.DbNull` or `Prisma.JsonNull`
 *
 * @see https://www.prisma.io/docs/concepts/components/prisma-client/working-with-fields/working-with-json-fields#filtering-on-a-json-field
 */
export const AnyNull = runtime.AnyNull


export const ModelName = {
  User: 'User',
  Session: 'Session',
  Account: 'Account',
  Verification: 'Verification',
  Tenant: 'Tenant',
  TenantMember: 'TenantMember',
  TenantInvitation: 'TenantInvitation',
  SubscriptionPlan: 'SubscriptionPlan',
  Subscription: 'Subscription',
  SubscriptionHistory: 'SubscriptionHistory',
  Invoice: 'Invoice',
  AcademicClass: 'AcademicClass',
  AcademicSubject: 'AcademicSubject',
  AcademicChapter: 'AcademicChapter',
  AcademicTopic: 'AcademicTopic',
  AcademicSubTopic: 'AcademicSubTopic',
  Mcq: 'Mcq',
  Cq: 'Cq',
  AuditLog: 'AuditLog',
  SystemSetting: 'SystemSetting',
  Notification: 'Notification'
} as const

export type ModelName = (typeof ModelName)[keyof typeof ModelName]

/*
 * Enums
 */

export const TransactionIsolationLevel = {
  ReadUncommitted: 'ReadUncommitted',
  ReadCommitted: 'ReadCommitted',
  RepeatableRead: 'RepeatableRead',
  Serializable: 'Serializable'
} as const

export type TransactionIsolationLevel = (typeof TransactionIsolationLevel)[keyof typeof TransactionIsolationLevel]


export const UserScalarFieldEnum = {
  id: 'id',
  name: 'name',
  email: 'email',
  emailVerified: 'emailVerified',
  image: 'image',
  role: 'role',
  isActive: 'isActive',
  createdAt: 'createdAt',
  updatedAt: 'updatedAt',
  deletedAt: 'deletedAt'
} as const

export type UserScalarFieldEnum = (typeof UserScalarFieldEnum)[keyof typeof UserScalarFieldEnum]


export const SessionScalarFieldEnum = {
  id: 'id',
  expiresAt: 'expiresAt',
  token: 'token',
  createdAt: 'createdAt',
  updatedAt: 'updatedAt',
  ipAddress: 'ipAddress',
  userAgent: 'userAgent',
  userId: 'userId'
} as const

export type SessionScalarFieldEnum = (typeof SessionScalarFieldEnum)[keyof typeof SessionScalarFieldEnum]


export const AccountScalarFieldEnum = {
  id: 'id',
  accountId: 'accountId',
  providerId: 'providerId',
  userId: 'userId',
  accessToken: 'accessToken',
  refreshToken: 'refreshToken',
  idToken: 'idToken',
  accessTokenExpiresAt: 'accessTokenExpiresAt',
  refreshTokenExpiresAt: 'refreshTokenExpiresAt',
  scope: 'scope',
  password: 'password',
  createdAt: 'createdAt',
  updatedAt: 'updatedAt'
} as const

export type AccountScalarFieldEnum = (typeof AccountScalarFieldEnum)[keyof typeof AccountScalarFieldEnum]


export const VerificationScalarFieldEnum = {
  id: 'id',
  identifier: 'identifier',
  value: 'value',
  expiresAt: 'expiresAt',
  createdAt: 'createdAt',
  updatedAt: 'updatedAt'
} as const

export type VerificationScalarFieldEnum = (typeof VerificationScalarFieldEnum)[keyof typeof VerificationScalarFieldEnum]


export const TenantScalarFieldEnum = {
  id: 'id',
  name: 'name',
  slug: 'slug',
  description: 'description',
  logo: 'logo',
  type: 'type',
  email: 'email',
  phone: 'phone',
  address: 'address',
  city: 'city',
  state: 'state',
  postalCode: 'postalCode',
  subdomain: 'subdomain',
  customDomain: 'customDomain',
  customDomainVerified: 'customDomainVerified',
  databaseName: 'databaseName',
  connectionString: 'connectionString',
  databaseStatus: 'databaseStatus',
  studentCount: 'studentCount',
  teacherCount: 'teacherCount',
  examCount: 'examCount',
  storageUsedMB: 'storageUsedMB',
  isActive: 'isActive',
  isSuspended: 'isSuspended',
  suspendReason: 'suspendReason',
  currentAcademicYear: 'currentAcademicYear',
  metadata: 'metadata',
  createdById: 'createdById',
  createdAt: 'createdAt',
  updatedAt: 'updatedAt',
  deletedAt: 'deletedAt',
  customStudentLimit: 'customStudentLimit',
  customTeacherLimit: 'customTeacherLimit',
  customExamLimit: 'customExamLimit',
  customStorageLimit: 'customStorageLimit'
} as const

export type TenantScalarFieldEnum = (typeof TenantScalarFieldEnum)[keyof typeof TenantScalarFieldEnum]


export const TenantMemberScalarFieldEnum = {
  id: 'id',
  userId: 'userId',
  tenantId: 'tenantId',
  role: 'role',
  isActive: 'isActive',
  joinedAt: 'joinedAt',
  updatedAt: 'updatedAt'
} as const

export type TenantMemberScalarFieldEnum = (typeof TenantMemberScalarFieldEnum)[keyof typeof TenantMemberScalarFieldEnum]


export const TenantInvitationScalarFieldEnum = {
  id: 'id',
  tenantId: 'tenantId',
  email: 'email',
  role: 'role',
  token: 'token',
  expiresAt: 'expiresAt',
  invitedBy: 'invitedBy',
  acceptedAt: 'acceptedAt',
  acceptedBy: 'acceptedBy',
  message: 'message',
  name: 'name',
  status: 'status',
  createdAt: 'createdAt',
  updatedAt: 'updatedAt'
} as const

export type TenantInvitationScalarFieldEnum = (typeof TenantInvitationScalarFieldEnum)[keyof typeof TenantInvitationScalarFieldEnum]


export const SubscriptionPlanScalarFieldEnum = {
  id: 'id',
  name: 'name',
  displayName: 'displayName',
  description: 'description',
  monthlyPriceBDT: 'monthlyPriceBDT',
  yearlyPriceBDT: 'yearlyPriceBDT',
  monthlyPriceUSD: 'monthlyPriceUSD',
  yearlyPriceUSD: 'yearlyPriceUSD',
  features: 'features',
  isActive: 'isActive',
  isPopular: 'isPopular',
  defaultStudentLimit: 'defaultStudentLimit',
  defaultTeacherLimit: 'defaultTeacherLimit',
  defaultExamLimit: 'defaultExamLimit',
  defaultStorageLimit: 'defaultStorageLimit',
  createdAt: 'createdAt',
  updatedAt: 'updatedAt'
} as const

export type SubscriptionPlanScalarFieldEnum = (typeof SubscriptionPlanScalarFieldEnum)[keyof typeof SubscriptionPlanScalarFieldEnum]


export const SubscriptionScalarFieldEnum = {
  id: 'id',
  tenantId: 'tenantId',
  planId: 'planId',
  status: 'status',
  currentPeriodStart: 'currentPeriodStart',
  currentPeriodEnd: 'currentPeriodEnd',
  trialEndsAt: 'trialEndsAt',
  billingCycle: 'billingCycle',
  currency: 'currency',
  pricePerMonth: 'pricePerMonth',
  pricePerYear: 'pricePerYear',
  paymentProvider: 'paymentProvider',
  externalId: 'externalId',
  cancelAtPeriodEnd: 'cancelAtPeriodEnd',
  canceledAt: 'canceledAt',
  cancelReason: 'cancelReason',
  customStudentLimit: 'customStudentLimit',
  customTeacherLimit: 'customTeacherLimit',
  customExamLimit: 'customExamLimit',
  customStorageLimit: 'customStorageLimit',
  createdAt: 'createdAt',
  updatedAt: 'updatedAt'
} as const

export type SubscriptionScalarFieldEnum = (typeof SubscriptionScalarFieldEnum)[keyof typeof SubscriptionScalarFieldEnum]


export const SubscriptionHistoryScalarFieldEnum = {
  id: 'id',
  subscriptionId: 'subscriptionId',
  event: 'event',
  fromPlanId: 'fromPlanId',
  toPlanId: 'toPlanId',
  fromStatus: 'fromStatus',
  toStatus: 'toStatus',
  reason: 'reason',
  metadata: 'metadata',
  createdBy: 'createdBy',
  createdAt: 'createdAt'
} as const

export type SubscriptionHistoryScalarFieldEnum = (typeof SubscriptionHistoryScalarFieldEnum)[keyof typeof SubscriptionHistoryScalarFieldEnum]


export const InvoiceScalarFieldEnum = {
  id: 'id',
  tenantId: 'tenantId',
  invoiceNumber: 'invoiceNumber',
  amount: 'amount',
  currency: 'currency',
  status: 'status',
  periodStart: 'periodStart',
  periodEnd: 'periodEnd',
  dueDate: 'dueDate',
  paidAt: 'paidAt',
  paymentMethod: 'paymentMethod',
  paymentProvider: 'paymentProvider',
  paymentReference: 'paymentReference',
  pdfUrl: 'pdfUrl',
  lineItems: 'lineItems',
  description: 'description',
  notes: 'notes',
  createdAt: 'createdAt',
  updatedAt: 'updatedAt'
} as const

export type InvoiceScalarFieldEnum = (typeof InvoiceScalarFieldEnum)[keyof typeof InvoiceScalarFieldEnum]


export const AcademicClassScalarFieldEnum = {
  id: 'id',
  name: 'name',
  level: 'level',
  displayName: 'displayName',
  position: 'position',
  isActive: 'isActive',
  createdAt: 'createdAt',
  updatedAt: 'updatedAt'
} as const

export type AcademicClassScalarFieldEnum = (typeof AcademicClassScalarFieldEnum)[keyof typeof AcademicClassScalarFieldEnum]


export const AcademicSubjectScalarFieldEnum = {
  id: 'id',
  name: 'name',
  displayName: 'displayName',
  code: 'code',
  group: 'group',
  position: 'position',
  isActive: 'isActive',
  classId: 'classId',
  createdAt: 'createdAt',
  updatedAt: 'updatedAt'
} as const

export type AcademicSubjectScalarFieldEnum = (typeof AcademicSubjectScalarFieldEnum)[keyof typeof AcademicSubjectScalarFieldEnum]


export const AcademicChapterScalarFieldEnum = {
  id: 'id',
  name: 'name',
  displayName: 'displayName',
  position: 'position',
  isActive: 'isActive',
  subjectId: 'subjectId',
  createdAt: 'createdAt',
  updatedAt: 'updatedAt'
} as const

export type AcademicChapterScalarFieldEnum = (typeof AcademicChapterScalarFieldEnum)[keyof typeof AcademicChapterScalarFieldEnum]


export const AcademicTopicScalarFieldEnum = {
  id: 'id',
  name: 'name',
  displayName: 'displayName',
  position: 'position',
  isActive: 'isActive',
  chapterId: 'chapterId',
  createdAt: 'createdAt',
  updatedAt: 'updatedAt'
} as const

export type AcademicTopicScalarFieldEnum = (typeof AcademicTopicScalarFieldEnum)[keyof typeof AcademicTopicScalarFieldEnum]


export const AcademicSubTopicScalarFieldEnum = {
  id: 'id',
  name: 'name',
  displayName: 'displayName',
  position: 'position',
  isActive: 'isActive',
  topicId: 'topicId',
  createdAt: 'createdAt',
  updatedAt: 'updatedAt'
} as const

export type AcademicSubTopicScalarFieldEnum = (typeof AcademicSubTopicScalarFieldEnum)[keyof typeof AcademicSubTopicScalarFieldEnum]


export const McqScalarFieldEnum = {
  id: 'id',
  question: 'question',
  answer: 'answer',
  options: 'options',
  statements: 'statements',
  type: 'type',
  isMath: 'isMath',
  reference: 'reference',
  explanation: 'explanation',
  session: 'session',
  source: 'source',
  questionUrl: 'questionUrl',
  context: 'context',
  contextUrl: 'contextUrl',
  subjectId: 'subjectId',
  chapterId: 'chapterId',
  topicId: 'topicId',
  subTopicId: 'subTopicId',
  createdAt: 'createdAt',
  updatedAt: 'updatedAt'
} as const

export type McqScalarFieldEnum = (typeof McqScalarFieldEnum)[keyof typeof McqScalarFieldEnum]


export const CqScalarFieldEnum = {
  id: 'id',
  questionA: 'questionA',
  questionB: 'questionB',
  questionC: 'questionC',
  questionD: 'questionD',
  context: 'context',
  marks: 'marks',
  isActive: 'isActive',
  classId: 'classId',
  subjectId: 'subjectId',
  chapterId: 'chapterId',
  topicId: 'topicId',
  subTopicId: 'subTopicId',
  createdAt: 'createdAt',
  updatedAt: 'updatedAt'
} as const

export type CqScalarFieldEnum = (typeof CqScalarFieldEnum)[keyof typeof CqScalarFieldEnum]


export const AuditLogScalarFieldEnum = {
  id: 'id',
  action: 'action',
  entity: 'entity',
  entityId: 'entityId',
  description: 'description',
  metadata: 'metadata',
  ipAddress: 'ipAddress',
  userAgent: 'userAgent',
  userId: 'userId',
  tenantId: 'tenantId',
  createdAt: 'createdAt'
} as const

export type AuditLogScalarFieldEnum = (typeof AuditLogScalarFieldEnum)[keyof typeof AuditLogScalarFieldEnum]


export const SystemSettingScalarFieldEnum = {
  id: 'id',
  key: 'key',
  value: 'value',
  type: 'type',
  description: 'description',
  category: 'category',
  createdAt: 'createdAt',
  updatedAt: 'updatedAt'
} as const

export type SystemSettingScalarFieldEnum = (typeof SystemSettingScalarFieldEnum)[keyof typeof SystemSettingScalarFieldEnum]


export const NotificationScalarFieldEnum = {
  id: 'id',
  title: 'title',
  message: 'message',
  type: 'type',
  read: 'read',
  actionUrl: 'actionUrl',
  actionLabel: 'actionLabel',
  userId: 'userId',
  tenantId: 'tenantId',
  createdAt: 'createdAt',
  updatedAt: 'updatedAt'
} as const

export type NotificationScalarFieldEnum = (typeof NotificationScalarFieldEnum)[keyof typeof NotificationScalarFieldEnum]


export const SortOrder = {
  asc: 'asc',
  desc: 'desc'
} as const

export type SortOrder = (typeof SortOrder)[keyof typeof SortOrder]


export const JsonNullValueInput = {
  JsonNull: 'JsonNull'
} as const

export type JsonNullValueInput = (typeof JsonNullValueInput)[keyof typeof JsonNullValueInput]


export const NullableJsonNullValueInput = {
  DbNull: 'DbNull',
  JsonNull: 'JsonNull'
} as const

export type NullableJsonNullValueInput = (typeof NullableJsonNullValueInput)[keyof typeof NullableJsonNullValueInput]


export const QueryMode = {
  default: 'default',
  insensitive: 'insensitive'
} as const

export type QueryMode = (typeof QueryMode)[keyof typeof QueryMode]


export const NullsOrder = {
  first: 'first',
  last: 'last'
} as const

export type NullsOrder = (typeof NullsOrder)[keyof typeof NullsOrder]


export const JsonNullValueFilter = {
  DbNull: 'DbNull',
  JsonNull: 'JsonNull',
  AnyNull: 'AnyNull'
} as const

export type JsonNullValueFilter = (typeof JsonNullValueFilter)[keyof typeof JsonNullValueFilter]

