
/* !!! This is code generated by Prisma. Do not edit directly. !!! */
/* eslint-disable */
// biome-ignore-all lint: generated file
// @ts-nocheck 
/*
 * This file exports the `AcademicClass` model and its related types.
 *
 * 🟢 You can import this file directly.
 */
import type * as runtime from "@prisma/client/runtime/client"
import type * as $Enums from "../enums"
import type * as Prisma from "../internal/prismaNamespace"

/**
 * Model AcademicClass
 * 
 */
export type AcademicClassModel = runtime.Types.Result.DefaultSelection<Prisma.$AcademicClassPayload>

export type AggregateAcademicClass = {
  _count: AcademicClassCountAggregateOutputType | null
  _avg: AcademicClassAvgAggregateOutputType | null
  _sum: AcademicClassSumAggregateOutputType | null
  _min: AcademicClassMinAggregateOutputType | null
  _max: AcademicClassMaxAggregateOutputType | null
}

export type AcademicClassAvgAggregateOutputType = {
  position: number | null
}

export type AcademicClassSumAggregateOutputType = {
  position: number | null
}

export type AcademicClassMinAggregateOutputType = {
  id: string | null
  name: string | null
  level: string | null
  displayName: string | null
  position: number | null
  isActive: boolean | null
  createdAt: Date | null
  updatedAt: Date | null
}

export type AcademicClassMaxAggregateOutputType = {
  id: string | null
  name: string | null
  level: string | null
  displayName: string | null
  position: number | null
  isActive: boolean | null
  createdAt: Date | null
  updatedAt: Date | null
}

export type AcademicClassCountAggregateOutputType = {
  id: number
  name: number
  level: number
  displayName: number
  position: number
  isActive: number
  createdAt: number
  updatedAt: number
  _all: number
}


export type AcademicClassAvgAggregateInputType = {
  position?: true
}

export type AcademicClassSumAggregateInputType = {
  position?: true
}

export type AcademicClassMinAggregateInputType = {
  id?: true
  name?: true
  level?: true
  displayName?: true
  position?: true
  isActive?: true
  createdAt?: true
  updatedAt?: true
}

export type AcademicClassMaxAggregateInputType = {
  id?: true
  name?: true
  level?: true
  displayName?: true
  position?: true
  isActive?: true
  createdAt?: true
  updatedAt?: true
}

export type AcademicClassCountAggregateInputType = {
  id?: true
  name?: true
  level?: true
  displayName?: true
  position?: true
  isActive?: true
  createdAt?: true
  updatedAt?: true
  _all?: true
}

export type AcademicClassAggregateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Filter which AcademicClass to aggregate.
   */
  where?: Prisma.AcademicClassWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of AcademicClasses to fetch.
   */
  orderBy?: Prisma.AcademicClassOrderByWithRelationInput | Prisma.AcademicClassOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the start position
   */
  cursor?: Prisma.AcademicClassWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` AcademicClasses from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` AcademicClasses.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Count returned AcademicClasses
  **/
  _count?: true | AcademicClassCountAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to average
  **/
  _avg?: AcademicClassAvgAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to sum
  **/
  _sum?: AcademicClassSumAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to find the minimum value
  **/
  _min?: AcademicClassMinAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to find the maximum value
  **/
  _max?: AcademicClassMaxAggregateInputType
}

export type GetAcademicClassAggregateType<T extends AcademicClassAggregateArgs> = {
      [P in keyof T & keyof AggregateAcademicClass]: P extends '_count' | 'count'
    ? T[P] extends true
      ? number
      : Prisma.GetScalarType<T[P], AggregateAcademicClass[P]>
    : Prisma.GetScalarType<T[P], AggregateAcademicClass[P]>
}




export type AcademicClassGroupByArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  where?: Prisma.AcademicClassWhereInput
  orderBy?: Prisma.AcademicClassOrderByWithAggregationInput | Prisma.AcademicClassOrderByWithAggregationInput[]
  by: Prisma.AcademicClassScalarFieldEnum[] | Prisma.AcademicClassScalarFieldEnum
  having?: Prisma.AcademicClassScalarWhereWithAggregatesInput
  take?: number
  skip?: number
  _count?: AcademicClassCountAggregateInputType | true
  _avg?: AcademicClassAvgAggregateInputType
  _sum?: AcademicClassSumAggregateInputType
  _min?: AcademicClassMinAggregateInputType
  _max?: AcademicClassMaxAggregateInputType
}

export type AcademicClassGroupByOutputType = {
  id: string
  name: string
  level: string
  displayName: string
  position: number
  isActive: boolean
  createdAt: Date
  updatedAt: Date
  _count: AcademicClassCountAggregateOutputType | null
  _avg: AcademicClassAvgAggregateOutputType | null
  _sum: AcademicClassSumAggregateOutputType | null
  _min: AcademicClassMinAggregateOutputType | null
  _max: AcademicClassMaxAggregateOutputType | null
}

type GetAcademicClassGroupByPayload<T extends AcademicClassGroupByArgs> = Prisma.PrismaPromise<
  Array<
    Prisma.PickEnumerable<AcademicClassGroupByOutputType, T['by']> &
      {
        [P in ((keyof T) & (keyof AcademicClassGroupByOutputType))]: P extends '_count'
          ? T[P] extends boolean
            ? number
            : Prisma.GetScalarType<T[P], AcademicClassGroupByOutputType[P]>
          : Prisma.GetScalarType<T[P], AcademicClassGroupByOutputType[P]>
      }
    >
  >



export type AcademicClassWhereInput = {
  AND?: Prisma.AcademicClassWhereInput | Prisma.AcademicClassWhereInput[]
  OR?: Prisma.AcademicClassWhereInput[]
  NOT?: Prisma.AcademicClassWhereInput | Prisma.AcademicClassWhereInput[]
  id?: Prisma.StringFilter<"AcademicClass"> | string
  name?: Prisma.StringFilter<"AcademicClass"> | string
  level?: Prisma.StringFilter<"AcademicClass"> | string
  displayName?: Prisma.StringFilter<"AcademicClass"> | string
  position?: Prisma.IntFilter<"AcademicClass"> | number
  isActive?: Prisma.BoolFilter<"AcademicClass"> | boolean
  createdAt?: Prisma.DateTimeFilter<"AcademicClass"> | Date | string
  updatedAt?: Prisma.DateTimeFilter<"AcademicClass"> | Date | string
  subjects?: Prisma.AcademicSubjectListRelationFilter
  cqs?: Prisma.CqListRelationFilter
}

export type AcademicClassOrderByWithRelationInput = {
  id?: Prisma.SortOrder
  name?: Prisma.SortOrder
  level?: Prisma.SortOrder
  displayName?: Prisma.SortOrder
  position?: Prisma.SortOrder
  isActive?: Prisma.SortOrder
  createdAt?: Prisma.SortOrder
  updatedAt?: Prisma.SortOrder
  subjects?: Prisma.AcademicSubjectOrderByRelationAggregateInput
  cqs?: Prisma.CqOrderByRelationAggregateInput
}

export type AcademicClassWhereUniqueInput = Prisma.AtLeast<{
  id?: string
  name?: string
  AND?: Prisma.AcademicClassWhereInput | Prisma.AcademicClassWhereInput[]
  OR?: Prisma.AcademicClassWhereInput[]
  NOT?: Prisma.AcademicClassWhereInput | Prisma.AcademicClassWhereInput[]
  level?: Prisma.StringFilter<"AcademicClass"> | string
  displayName?: Prisma.StringFilter<"AcademicClass"> | string
  position?: Prisma.IntFilter<"AcademicClass"> | number
  isActive?: Prisma.BoolFilter<"AcademicClass"> | boolean
  createdAt?: Prisma.DateTimeFilter<"AcademicClass"> | Date | string
  updatedAt?: Prisma.DateTimeFilter<"AcademicClass"> | Date | string
  subjects?: Prisma.AcademicSubjectListRelationFilter
  cqs?: Prisma.CqListRelationFilter
}, "id" | "name">

export type AcademicClassOrderByWithAggregationInput = {
  id?: Prisma.SortOrder
  name?: Prisma.SortOrder
  level?: Prisma.SortOrder
  displayName?: Prisma.SortOrder
  position?: Prisma.SortOrder
  isActive?: Prisma.SortOrder
  createdAt?: Prisma.SortOrder
  updatedAt?: Prisma.SortOrder
  _count?: Prisma.AcademicClassCountOrderByAggregateInput
  _avg?: Prisma.AcademicClassAvgOrderByAggregateInput
  _max?: Prisma.AcademicClassMaxOrderByAggregateInput
  _min?: Prisma.AcademicClassMinOrderByAggregateInput
  _sum?: Prisma.AcademicClassSumOrderByAggregateInput
}

export type AcademicClassScalarWhereWithAggregatesInput = {
  AND?: Prisma.AcademicClassScalarWhereWithAggregatesInput | Prisma.AcademicClassScalarWhereWithAggregatesInput[]
  OR?: Prisma.AcademicClassScalarWhereWithAggregatesInput[]
  NOT?: Prisma.AcademicClassScalarWhereWithAggregatesInput | Prisma.AcademicClassScalarWhereWithAggregatesInput[]
  id?: Prisma.StringWithAggregatesFilter<"AcademicClass"> | string
  name?: Prisma.StringWithAggregatesFilter<"AcademicClass"> | string
  level?: Prisma.StringWithAggregatesFilter<"AcademicClass"> | string
  displayName?: Prisma.StringWithAggregatesFilter<"AcademicClass"> | string
  position?: Prisma.IntWithAggregatesFilter<"AcademicClass"> | number
  isActive?: Prisma.BoolWithAggregatesFilter<"AcademicClass"> | boolean
  createdAt?: Prisma.DateTimeWithAggregatesFilter<"AcademicClass"> | Date | string
  updatedAt?: Prisma.DateTimeWithAggregatesFilter<"AcademicClass"> | Date | string
}

export type AcademicClassCreateInput = {
  id?: string
  name: string
  level: string
  displayName: string
  position?: number
  isActive?: boolean
  createdAt?: Date | string
  updatedAt?: Date | string
  subjects?: Prisma.AcademicSubjectCreateNestedManyWithoutClassInput
  cqs?: Prisma.CqCreateNestedManyWithoutClassInput
}

export type AcademicClassUncheckedCreateInput = {
  id?: string
  name: string
  level: string
  displayName: string
  position?: number
  isActive?: boolean
  createdAt?: Date | string
  updatedAt?: Date | string
  subjects?: Prisma.AcademicSubjectUncheckedCreateNestedManyWithoutClassInput
  cqs?: Prisma.CqUncheckedCreateNestedManyWithoutClassInput
}

export type AcademicClassUpdateInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  name?: Prisma.StringFieldUpdateOperationsInput | string
  level?: Prisma.StringFieldUpdateOperationsInput | string
  displayName?: Prisma.StringFieldUpdateOperationsInput | string
  position?: Prisma.IntFieldUpdateOperationsInput | number
  isActive?: Prisma.BoolFieldUpdateOperationsInput | boolean
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  subjects?: Prisma.AcademicSubjectUpdateManyWithoutClassNestedInput
  cqs?: Prisma.CqUpdateManyWithoutClassNestedInput
}

export type AcademicClassUncheckedUpdateInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  name?: Prisma.StringFieldUpdateOperationsInput | string
  level?: Prisma.StringFieldUpdateOperationsInput | string
  displayName?: Prisma.StringFieldUpdateOperationsInput | string
  position?: Prisma.IntFieldUpdateOperationsInput | number
  isActive?: Prisma.BoolFieldUpdateOperationsInput | boolean
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  subjects?: Prisma.AcademicSubjectUncheckedUpdateManyWithoutClassNestedInput
  cqs?: Prisma.CqUncheckedUpdateManyWithoutClassNestedInput
}

export type AcademicClassCreateManyInput = {
  id?: string
  name: string
  level: string
  displayName: string
  position?: number
  isActive?: boolean
  createdAt?: Date | string
  updatedAt?: Date | string
}

export type AcademicClassUpdateManyMutationInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  name?: Prisma.StringFieldUpdateOperationsInput | string
  level?: Prisma.StringFieldUpdateOperationsInput | string
  displayName?: Prisma.StringFieldUpdateOperationsInput | string
  position?: Prisma.IntFieldUpdateOperationsInput | number
  isActive?: Prisma.BoolFieldUpdateOperationsInput | boolean
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type AcademicClassUncheckedUpdateManyInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  name?: Prisma.StringFieldUpdateOperationsInput | string
  level?: Prisma.StringFieldUpdateOperationsInput | string
  displayName?: Prisma.StringFieldUpdateOperationsInput | string
  position?: Prisma.IntFieldUpdateOperationsInput | number
  isActive?: Prisma.BoolFieldUpdateOperationsInput | boolean
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type AcademicClassCountOrderByAggregateInput = {
  id?: Prisma.SortOrder
  name?: Prisma.SortOrder
  level?: Prisma.SortOrder
  displayName?: Prisma.SortOrder
  position?: Prisma.SortOrder
  isActive?: Prisma.SortOrder
  createdAt?: Prisma.SortOrder
  updatedAt?: Prisma.SortOrder
}

export type AcademicClassAvgOrderByAggregateInput = {
  position?: Prisma.SortOrder
}

export type AcademicClassMaxOrderByAggregateInput = {
  id?: Prisma.SortOrder
  name?: Prisma.SortOrder
  level?: Prisma.SortOrder
  displayName?: Prisma.SortOrder
  position?: Prisma.SortOrder
  isActive?: Prisma.SortOrder
  createdAt?: Prisma.SortOrder
  updatedAt?: Prisma.SortOrder
}

export type AcademicClassMinOrderByAggregateInput = {
  id?: Prisma.SortOrder
  name?: Prisma.SortOrder
  level?: Prisma.SortOrder
  displayName?: Prisma.SortOrder
  position?: Prisma.SortOrder
  isActive?: Prisma.SortOrder
  createdAt?: Prisma.SortOrder
  updatedAt?: Prisma.SortOrder
}

export type AcademicClassSumOrderByAggregateInput = {
  position?: Prisma.SortOrder
}

export type AcademicClassScalarRelationFilter = {
  is?: Prisma.AcademicClassWhereInput
  isNot?: Prisma.AcademicClassWhereInput
}

export type AcademicClassCreateNestedOneWithoutSubjectsInput = {
  create?: Prisma.XOR<Prisma.AcademicClassCreateWithoutSubjectsInput, Prisma.AcademicClassUncheckedCreateWithoutSubjectsInput>
  connectOrCreate?: Prisma.AcademicClassCreateOrConnectWithoutSubjectsInput
  connect?: Prisma.AcademicClassWhereUniqueInput
}

export type AcademicClassUpdateOneRequiredWithoutSubjectsNestedInput = {
  create?: Prisma.XOR<Prisma.AcademicClassCreateWithoutSubjectsInput, Prisma.AcademicClassUncheckedCreateWithoutSubjectsInput>
  connectOrCreate?: Prisma.AcademicClassCreateOrConnectWithoutSubjectsInput
  upsert?: Prisma.AcademicClassUpsertWithoutSubjectsInput
  connect?: Prisma.AcademicClassWhereUniqueInput
  update?: Prisma.XOR<Prisma.XOR<Prisma.AcademicClassUpdateToOneWithWhereWithoutSubjectsInput, Prisma.AcademicClassUpdateWithoutSubjectsInput>, Prisma.AcademicClassUncheckedUpdateWithoutSubjectsInput>
}

export type AcademicClassCreateNestedOneWithoutCqsInput = {
  create?: Prisma.XOR<Prisma.AcademicClassCreateWithoutCqsInput, Prisma.AcademicClassUncheckedCreateWithoutCqsInput>
  connectOrCreate?: Prisma.AcademicClassCreateOrConnectWithoutCqsInput
  connect?: Prisma.AcademicClassWhereUniqueInput
}

export type AcademicClassUpdateOneRequiredWithoutCqsNestedInput = {
  create?: Prisma.XOR<Prisma.AcademicClassCreateWithoutCqsInput, Prisma.AcademicClassUncheckedCreateWithoutCqsInput>
  connectOrCreate?: Prisma.AcademicClassCreateOrConnectWithoutCqsInput
  upsert?: Prisma.AcademicClassUpsertWithoutCqsInput
  connect?: Prisma.AcademicClassWhereUniqueInput
  update?: Prisma.XOR<Prisma.XOR<Prisma.AcademicClassUpdateToOneWithWhereWithoutCqsInput, Prisma.AcademicClassUpdateWithoutCqsInput>, Prisma.AcademicClassUncheckedUpdateWithoutCqsInput>
}

export type AcademicClassCreateWithoutSubjectsInput = {
  id?: string
  name: string
  level: string
  displayName: string
  position?: number
  isActive?: boolean
  createdAt?: Date | string
  updatedAt?: Date | string
  cqs?: Prisma.CqCreateNestedManyWithoutClassInput
}

export type AcademicClassUncheckedCreateWithoutSubjectsInput = {
  id?: string
  name: string
  level: string
  displayName: string
  position?: number
  isActive?: boolean
  createdAt?: Date | string
  updatedAt?: Date | string
  cqs?: Prisma.CqUncheckedCreateNestedManyWithoutClassInput
}

export type AcademicClassCreateOrConnectWithoutSubjectsInput = {
  where: Prisma.AcademicClassWhereUniqueInput
  create: Prisma.XOR<Prisma.AcademicClassCreateWithoutSubjectsInput, Prisma.AcademicClassUncheckedCreateWithoutSubjectsInput>
}

export type AcademicClassUpsertWithoutSubjectsInput = {
  update: Prisma.XOR<Prisma.AcademicClassUpdateWithoutSubjectsInput, Prisma.AcademicClassUncheckedUpdateWithoutSubjectsInput>
  create: Prisma.XOR<Prisma.AcademicClassCreateWithoutSubjectsInput, Prisma.AcademicClassUncheckedCreateWithoutSubjectsInput>
  where?: Prisma.AcademicClassWhereInput
}

export type AcademicClassUpdateToOneWithWhereWithoutSubjectsInput = {
  where?: Prisma.AcademicClassWhereInput
  data: Prisma.XOR<Prisma.AcademicClassUpdateWithoutSubjectsInput, Prisma.AcademicClassUncheckedUpdateWithoutSubjectsInput>
}

export type AcademicClassUpdateWithoutSubjectsInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  name?: Prisma.StringFieldUpdateOperationsInput | string
  level?: Prisma.StringFieldUpdateOperationsInput | string
  displayName?: Prisma.StringFieldUpdateOperationsInput | string
  position?: Prisma.IntFieldUpdateOperationsInput | number
  isActive?: Prisma.BoolFieldUpdateOperationsInput | boolean
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  cqs?: Prisma.CqUpdateManyWithoutClassNestedInput
}

export type AcademicClassUncheckedUpdateWithoutSubjectsInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  name?: Prisma.StringFieldUpdateOperationsInput | string
  level?: Prisma.StringFieldUpdateOperationsInput | string
  displayName?: Prisma.StringFieldUpdateOperationsInput | string
  position?: Prisma.IntFieldUpdateOperationsInput | number
  isActive?: Prisma.BoolFieldUpdateOperationsInput | boolean
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  cqs?: Prisma.CqUncheckedUpdateManyWithoutClassNestedInput
}

export type AcademicClassCreateWithoutCqsInput = {
  id?: string
  name: string
  level: string
  displayName: string
  position?: number
  isActive?: boolean
  createdAt?: Date | string
  updatedAt?: Date | string
  subjects?: Prisma.AcademicSubjectCreateNestedManyWithoutClassInput
}

export type AcademicClassUncheckedCreateWithoutCqsInput = {
  id?: string
  name: string
  level: string
  displayName: string
  position?: number
  isActive?: boolean
  createdAt?: Date | string
  updatedAt?: Date | string
  subjects?: Prisma.AcademicSubjectUncheckedCreateNestedManyWithoutClassInput
}

export type AcademicClassCreateOrConnectWithoutCqsInput = {
  where: Prisma.AcademicClassWhereUniqueInput
  create: Prisma.XOR<Prisma.AcademicClassCreateWithoutCqsInput, Prisma.AcademicClassUncheckedCreateWithoutCqsInput>
}

export type AcademicClassUpsertWithoutCqsInput = {
  update: Prisma.XOR<Prisma.AcademicClassUpdateWithoutCqsInput, Prisma.AcademicClassUncheckedUpdateWithoutCqsInput>
  create: Prisma.XOR<Prisma.AcademicClassCreateWithoutCqsInput, Prisma.AcademicClassUncheckedCreateWithoutCqsInput>
  where?: Prisma.AcademicClassWhereInput
}

export type AcademicClassUpdateToOneWithWhereWithoutCqsInput = {
  where?: Prisma.AcademicClassWhereInput
  data: Prisma.XOR<Prisma.AcademicClassUpdateWithoutCqsInput, Prisma.AcademicClassUncheckedUpdateWithoutCqsInput>
}

export type AcademicClassUpdateWithoutCqsInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  name?: Prisma.StringFieldUpdateOperationsInput | string
  level?: Prisma.StringFieldUpdateOperationsInput | string
  displayName?: Prisma.StringFieldUpdateOperationsInput | string
  position?: Prisma.IntFieldUpdateOperationsInput | number
  isActive?: Prisma.BoolFieldUpdateOperationsInput | boolean
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  subjects?: Prisma.AcademicSubjectUpdateManyWithoutClassNestedInput
}

export type AcademicClassUncheckedUpdateWithoutCqsInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  name?: Prisma.StringFieldUpdateOperationsInput | string
  level?: Prisma.StringFieldUpdateOperationsInput | string
  displayName?: Prisma.StringFieldUpdateOperationsInput | string
  position?: Prisma.IntFieldUpdateOperationsInput | number
  isActive?: Prisma.BoolFieldUpdateOperationsInput | boolean
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  subjects?: Prisma.AcademicSubjectUncheckedUpdateManyWithoutClassNestedInput
}


/**
 * Count Type AcademicClassCountOutputType
 */

export type AcademicClassCountOutputType = {
  subjects: number
  cqs: number
}

export type AcademicClassCountOutputTypeSelect<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  subjects?: boolean | AcademicClassCountOutputTypeCountSubjectsArgs
  cqs?: boolean | AcademicClassCountOutputTypeCountCqsArgs
}

/**
 * AcademicClassCountOutputType without action
 */
export type AcademicClassCountOutputTypeDefaultArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the AcademicClassCountOutputType
   */
  select?: Prisma.AcademicClassCountOutputTypeSelect<ExtArgs> | null
}

/**
 * AcademicClassCountOutputType without action
 */
export type AcademicClassCountOutputTypeCountSubjectsArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  where?: Prisma.AcademicSubjectWhereInput
}

/**
 * AcademicClassCountOutputType without action
 */
export type AcademicClassCountOutputTypeCountCqsArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  where?: Prisma.CqWhereInput
}


export type AcademicClassSelect<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  name?: boolean
  level?: boolean
  displayName?: boolean
  position?: boolean
  isActive?: boolean
  createdAt?: boolean
  updatedAt?: boolean
  subjects?: boolean | Prisma.AcademicClass$subjectsArgs<ExtArgs>
  cqs?: boolean | Prisma.AcademicClass$cqsArgs<ExtArgs>
  _count?: boolean | Prisma.AcademicClassCountOutputTypeDefaultArgs<ExtArgs>
}, ExtArgs["result"]["academicClass"]>

export type AcademicClassSelectCreateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  name?: boolean
  level?: boolean
  displayName?: boolean
  position?: boolean
  isActive?: boolean
  createdAt?: boolean
  updatedAt?: boolean
}, ExtArgs["result"]["academicClass"]>

export type AcademicClassSelectUpdateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  name?: boolean
  level?: boolean
  displayName?: boolean
  position?: boolean
  isActive?: boolean
  createdAt?: boolean
  updatedAt?: boolean
}, ExtArgs["result"]["academicClass"]>

export type AcademicClassSelectScalar = {
  id?: boolean
  name?: boolean
  level?: boolean
  displayName?: boolean
  position?: boolean
  isActive?: boolean
  createdAt?: boolean
  updatedAt?: boolean
}

export type AcademicClassOmit<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetOmit<"id" | "name" | "level" | "displayName" | "position" | "isActive" | "createdAt" | "updatedAt", ExtArgs["result"]["academicClass"]>
export type AcademicClassInclude<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  subjects?: boolean | Prisma.AcademicClass$subjectsArgs<ExtArgs>
  cqs?: boolean | Prisma.AcademicClass$cqsArgs<ExtArgs>
  _count?: boolean | Prisma.AcademicClassCountOutputTypeDefaultArgs<ExtArgs>
}
export type AcademicClassIncludeCreateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {}
export type AcademicClassIncludeUpdateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {}

export type $AcademicClassPayload<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  name: "AcademicClass"
  objects: {
    subjects: Prisma.$AcademicSubjectPayload<ExtArgs>[]
    cqs: Prisma.$CqPayload<ExtArgs>[]
  }
  scalars: runtime.Types.Extensions.GetPayloadResult<{
    id: string
    name: string
    level: string
    displayName: string
    position: number
    isActive: boolean
    createdAt: Date
    updatedAt: Date
  }, ExtArgs["result"]["academicClass"]>
  composites: {}
}

export type AcademicClassGetPayload<S extends boolean | null | undefined | AcademicClassDefaultArgs> = runtime.Types.Result.GetResult<Prisma.$AcademicClassPayload, S>

export type AcademicClassCountArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> =
  Omit<AcademicClassFindManyArgs, 'select' | 'include' | 'distinct' | 'omit'> & {
    select?: AcademicClassCountAggregateInputType | true
  }

export interface AcademicClassDelegate<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs, GlobalOmitOptions = {}> {
  [K: symbol]: { types: Prisma.TypeMap<ExtArgs>['model']['AcademicClass'], meta: { name: 'AcademicClass' } }
  /**
   * Find zero or one AcademicClass that matches the filter.
   * @param {AcademicClassFindUniqueArgs} args - Arguments to find a AcademicClass
   * @example
   * // Get one AcademicClass
   * const academicClass = await prisma.academicClass.findUnique({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findUnique<T extends AcademicClassFindUniqueArgs>(args: Prisma.SelectSubset<T, AcademicClassFindUniqueArgs<ExtArgs>>): Prisma.Prisma__AcademicClassClient<runtime.Types.Result.GetResult<Prisma.$AcademicClassPayload<ExtArgs>, T, "findUnique", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>

  /**
   * Find one AcademicClass that matches the filter or throw an error with `error.code='P2025'`
   * if no matches were found.
   * @param {AcademicClassFindUniqueOrThrowArgs} args - Arguments to find a AcademicClass
   * @example
   * // Get one AcademicClass
   * const academicClass = await prisma.academicClass.findUniqueOrThrow({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findUniqueOrThrow<T extends AcademicClassFindUniqueOrThrowArgs>(args: Prisma.SelectSubset<T, AcademicClassFindUniqueOrThrowArgs<ExtArgs>>): Prisma.Prisma__AcademicClassClient<runtime.Types.Result.GetResult<Prisma.$AcademicClassPayload<ExtArgs>, T, "findUniqueOrThrow", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Find the first AcademicClass that matches the filter.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {AcademicClassFindFirstArgs} args - Arguments to find a AcademicClass
   * @example
   * // Get one AcademicClass
   * const academicClass = await prisma.academicClass.findFirst({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findFirst<T extends AcademicClassFindFirstArgs>(args?: Prisma.SelectSubset<T, AcademicClassFindFirstArgs<ExtArgs>>): Prisma.Prisma__AcademicClassClient<runtime.Types.Result.GetResult<Prisma.$AcademicClassPayload<ExtArgs>, T, "findFirst", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>

  /**
   * Find the first AcademicClass that matches the filter or
   * throw `PrismaKnownClientError` with `P2025` code if no matches were found.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {AcademicClassFindFirstOrThrowArgs} args - Arguments to find a AcademicClass
   * @example
   * // Get one AcademicClass
   * const academicClass = await prisma.academicClass.findFirstOrThrow({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findFirstOrThrow<T extends AcademicClassFindFirstOrThrowArgs>(args?: Prisma.SelectSubset<T, AcademicClassFindFirstOrThrowArgs<ExtArgs>>): Prisma.Prisma__AcademicClassClient<runtime.Types.Result.GetResult<Prisma.$AcademicClassPayload<ExtArgs>, T, "findFirstOrThrow", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Find zero or more AcademicClasses that matches the filter.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {AcademicClassFindManyArgs} args - Arguments to filter and select certain fields only.
   * @example
   * // Get all AcademicClasses
   * const academicClasses = await prisma.academicClass.findMany()
   * 
   * // Get first 10 AcademicClasses
   * const academicClasses = await prisma.academicClass.findMany({ take: 10 })
   * 
   * // Only select the `id`
   * const academicClassWithIdOnly = await prisma.academicClass.findMany({ select: { id: true } })
   * 
   */
  findMany<T extends AcademicClassFindManyArgs>(args?: Prisma.SelectSubset<T, AcademicClassFindManyArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$AcademicClassPayload<ExtArgs>, T, "findMany", GlobalOmitOptions>>

  /**
   * Create a AcademicClass.
   * @param {AcademicClassCreateArgs} args - Arguments to create a AcademicClass.
   * @example
   * // Create one AcademicClass
   * const AcademicClass = await prisma.academicClass.create({
   *   data: {
   *     // ... data to create a AcademicClass
   *   }
   * })
   * 
   */
  create<T extends AcademicClassCreateArgs>(args: Prisma.SelectSubset<T, AcademicClassCreateArgs<ExtArgs>>): Prisma.Prisma__AcademicClassClient<runtime.Types.Result.GetResult<Prisma.$AcademicClassPayload<ExtArgs>, T, "create", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Create many AcademicClasses.
   * @param {AcademicClassCreateManyArgs} args - Arguments to create many AcademicClasses.
   * @example
   * // Create many AcademicClasses
   * const academicClass = await prisma.academicClass.createMany({
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   *     
   */
  createMany<T extends AcademicClassCreateManyArgs>(args?: Prisma.SelectSubset<T, AcademicClassCreateManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Create many AcademicClasses and returns the data saved in the database.
   * @param {AcademicClassCreateManyAndReturnArgs} args - Arguments to create many AcademicClasses.
   * @example
   * // Create many AcademicClasses
   * const academicClass = await prisma.academicClass.createManyAndReturn({
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * 
   * // Create many AcademicClasses and only return the `id`
   * const academicClassWithIdOnly = await prisma.academicClass.createManyAndReturn({
   *   select: { id: true },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * 
   */
  createManyAndReturn<T extends AcademicClassCreateManyAndReturnArgs>(args?: Prisma.SelectSubset<T, AcademicClassCreateManyAndReturnArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$AcademicClassPayload<ExtArgs>, T, "createManyAndReturn", GlobalOmitOptions>>

  /**
   * Delete a AcademicClass.
   * @param {AcademicClassDeleteArgs} args - Arguments to delete one AcademicClass.
   * @example
   * // Delete one AcademicClass
   * const AcademicClass = await prisma.academicClass.delete({
   *   where: {
   *     // ... filter to delete one AcademicClass
   *   }
   * })
   * 
   */
  delete<T extends AcademicClassDeleteArgs>(args: Prisma.SelectSubset<T, AcademicClassDeleteArgs<ExtArgs>>): Prisma.Prisma__AcademicClassClient<runtime.Types.Result.GetResult<Prisma.$AcademicClassPayload<ExtArgs>, T, "delete", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Update one AcademicClass.
   * @param {AcademicClassUpdateArgs} args - Arguments to update one AcademicClass.
   * @example
   * // Update one AcademicClass
   * const academicClass = await prisma.academicClass.update({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: {
   *     // ... provide data here
   *   }
   * })
   * 
   */
  update<T extends AcademicClassUpdateArgs>(args: Prisma.SelectSubset<T, AcademicClassUpdateArgs<ExtArgs>>): Prisma.Prisma__AcademicClassClient<runtime.Types.Result.GetResult<Prisma.$AcademicClassPayload<ExtArgs>, T, "update", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Delete zero or more AcademicClasses.
   * @param {AcademicClassDeleteManyArgs} args - Arguments to filter AcademicClasses to delete.
   * @example
   * // Delete a few AcademicClasses
   * const { count } = await prisma.academicClass.deleteMany({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   * 
   */
  deleteMany<T extends AcademicClassDeleteManyArgs>(args?: Prisma.SelectSubset<T, AcademicClassDeleteManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Update zero or more AcademicClasses.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {AcademicClassUpdateManyArgs} args - Arguments to update one or more rows.
   * @example
   * // Update many AcademicClasses
   * const academicClass = await prisma.academicClass.updateMany({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: {
   *     // ... provide data here
   *   }
   * })
   * 
   */
  updateMany<T extends AcademicClassUpdateManyArgs>(args: Prisma.SelectSubset<T, AcademicClassUpdateManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Update zero or more AcademicClasses and returns the data updated in the database.
   * @param {AcademicClassUpdateManyAndReturnArgs} args - Arguments to update many AcademicClasses.
   * @example
   * // Update many AcademicClasses
   * const academicClass = await prisma.academicClass.updateManyAndReturn({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * 
   * // Update zero or more AcademicClasses and only return the `id`
   * const academicClassWithIdOnly = await prisma.academicClass.updateManyAndReturn({
   *   select: { id: true },
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * 
   */
  updateManyAndReturn<T extends AcademicClassUpdateManyAndReturnArgs>(args: Prisma.SelectSubset<T, AcademicClassUpdateManyAndReturnArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$AcademicClassPayload<ExtArgs>, T, "updateManyAndReturn", GlobalOmitOptions>>

  /**
   * Create or update one AcademicClass.
   * @param {AcademicClassUpsertArgs} args - Arguments to update or create a AcademicClass.
   * @example
   * // Update or create a AcademicClass
   * const academicClass = await prisma.academicClass.upsert({
   *   create: {
   *     // ... data to create a AcademicClass
   *   },
   *   update: {
   *     // ... in case it already exists, update
   *   },
   *   where: {
   *     // ... the filter for the AcademicClass we want to update
   *   }
   * })
   */
  upsert<T extends AcademicClassUpsertArgs>(args: Prisma.SelectSubset<T, AcademicClassUpsertArgs<ExtArgs>>): Prisma.Prisma__AcademicClassClient<runtime.Types.Result.GetResult<Prisma.$AcademicClassPayload<ExtArgs>, T, "upsert", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>


  /**
   * Count the number of AcademicClasses.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {AcademicClassCountArgs} args - Arguments to filter AcademicClasses to count.
   * @example
   * // Count the number of AcademicClasses
   * const count = await prisma.academicClass.count({
   *   where: {
   *     // ... the filter for the AcademicClasses we want to count
   *   }
   * })
  **/
  count<T extends AcademicClassCountArgs>(
    args?: Prisma.Subset<T, AcademicClassCountArgs>,
  ): Prisma.PrismaPromise<
    T extends runtime.Types.Utils.Record<'select', any>
      ? T['select'] extends true
        ? number
        : Prisma.GetScalarType<T['select'], AcademicClassCountAggregateOutputType>
      : number
  >

  /**
   * Allows you to perform aggregations operations on a AcademicClass.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {AcademicClassAggregateArgs} args - Select which aggregations you would like to apply and on what fields.
   * @example
   * // Ordered by age ascending
   * // Where email contains prisma.io
   * // Limited to the 10 users
   * const aggregations = await prisma.user.aggregate({
   *   _avg: {
   *     age: true,
   *   },
   *   where: {
   *     email: {
   *       contains: "prisma.io",
   *     },
   *   },
   *   orderBy: {
   *     age: "asc",
   *   },
   *   take: 10,
   * })
  **/
  aggregate<T extends AcademicClassAggregateArgs>(args: Prisma.Subset<T, AcademicClassAggregateArgs>): Prisma.PrismaPromise<GetAcademicClassAggregateType<T>>

  /**
   * Group by AcademicClass.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {AcademicClassGroupByArgs} args - Group by arguments.
   * @example
   * // Group by city, order by createdAt, get count
   * const result = await prisma.user.groupBy({
   *   by: ['city', 'createdAt'],
   *   orderBy: {
   *     createdAt: true
   *   },
   *   _count: {
   *     _all: true
   *   },
   * })
   * 
  **/
  groupBy<
    T extends AcademicClassGroupByArgs,
    HasSelectOrTake extends Prisma.Or<
      Prisma.Extends<'skip', Prisma.Keys<T>>,
      Prisma.Extends<'take', Prisma.Keys<T>>
    >,
    OrderByArg extends Prisma.True extends HasSelectOrTake
      ? { orderBy: AcademicClassGroupByArgs['orderBy'] }
      : { orderBy?: AcademicClassGroupByArgs['orderBy'] },
    OrderFields extends Prisma.ExcludeUnderscoreKeys<Prisma.Keys<Prisma.MaybeTupleToUnion<T['orderBy']>>>,
    ByFields extends Prisma.MaybeTupleToUnion<T['by']>,
    ByValid extends Prisma.Has<ByFields, OrderFields>,
    HavingFields extends Prisma.GetHavingFields<T['having']>,
    HavingValid extends Prisma.Has<ByFields, HavingFields>,
    ByEmpty extends T['by'] extends never[] ? Prisma.True : Prisma.False,
    InputErrors extends ByEmpty extends Prisma.True
    ? `Error: "by" must not be empty.`
    : HavingValid extends Prisma.False
    ? {
        [P in HavingFields]: P extends ByFields
          ? never
          : P extends string
          ? `Error: Field "${P}" used in "having" needs to be provided in "by".`
          : [
              Error,
              'Field ',
              P,
              ` in "having" needs to be provided in "by"`,
            ]
      }[HavingFields]
    : 'take' extends Prisma.Keys<T>
    ? 'orderBy' extends Prisma.Keys<T>
      ? ByValid extends Prisma.True
        ? {}
        : {
            [P in OrderFields]: P extends ByFields
              ? never
              : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
          }[OrderFields]
      : 'Error: If you provide "take", you also need to provide "orderBy"'
    : 'skip' extends Prisma.Keys<T>
    ? 'orderBy' extends Prisma.Keys<T>
      ? ByValid extends Prisma.True
        ? {}
        : {
            [P in OrderFields]: P extends ByFields
              ? never
              : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
          }[OrderFields]
      : 'Error: If you provide "skip", you also need to provide "orderBy"'
    : ByValid extends Prisma.True
    ? {}
    : {
        [P in OrderFields]: P extends ByFields
          ? never
          : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
      }[OrderFields]
  >(args: Prisma.SubsetIntersection<T, AcademicClassGroupByArgs, OrderByArg> & InputErrors): {} extends InputErrors ? GetAcademicClassGroupByPayload<T> : Prisma.PrismaPromise<InputErrors>
/**
 * Fields of the AcademicClass model
 */
readonly fields: AcademicClassFieldRefs;
}

/**
 * The delegate class that acts as a "Promise-like" for AcademicClass.
 * Why is this prefixed with `Prisma__`?
 * Because we want to prevent naming conflicts as mentioned in
 * https://github.com/prisma/prisma-client-js/issues/707
 */
export interface Prisma__AcademicClassClient<T, Null = never, ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs, GlobalOmitOptions = {}> extends Prisma.PrismaPromise<T> {
  readonly [Symbol.toStringTag]: "PrismaPromise"
  subjects<T extends Prisma.AcademicClass$subjectsArgs<ExtArgs> = {}>(args?: Prisma.Subset<T, Prisma.AcademicClass$subjectsArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$AcademicSubjectPayload<ExtArgs>, T, "findMany", GlobalOmitOptions> | Null>
  cqs<T extends Prisma.AcademicClass$cqsArgs<ExtArgs> = {}>(args?: Prisma.Subset<T, Prisma.AcademicClass$cqsArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$CqPayload<ExtArgs>, T, "findMany", GlobalOmitOptions> | Null>
  /**
   * Attaches callbacks for the resolution and/or rejection of the Promise.
   * @param onfulfilled The callback to execute when the Promise is resolved.
   * @param onrejected The callback to execute when the Promise is rejected.
   * @returns A Promise for the completion of which ever callback is executed.
   */
  then<TResult1 = T, TResult2 = never>(onfulfilled?: ((value: T) => TResult1 | PromiseLike<TResult1>) | undefined | null, onrejected?: ((reason: any) => TResult2 | PromiseLike<TResult2>) | undefined | null): runtime.Types.Utils.JsPromise<TResult1 | TResult2>
  /**
   * Attaches a callback for only the rejection of the Promise.
   * @param onrejected The callback to execute when the Promise is rejected.
   * @returns A Promise for the completion of the callback.
   */
  catch<TResult = never>(onrejected?: ((reason: any) => TResult | PromiseLike<TResult>) | undefined | null): runtime.Types.Utils.JsPromise<T | TResult>
  /**
   * Attaches a callback that is invoked when the Promise is settled (fulfilled or rejected). The
   * resolved value cannot be modified from the callback.
   * @param onfinally The callback to execute when the Promise is settled (fulfilled or rejected).
   * @returns A Promise for the completion of the callback.
   */
  finally(onfinally?: (() => void) | undefined | null): runtime.Types.Utils.JsPromise<T>
}




/**
 * Fields of the AcademicClass model
 */
export interface AcademicClassFieldRefs {
  readonly id: Prisma.FieldRef<"AcademicClass", 'String'>
  readonly name: Prisma.FieldRef<"AcademicClass", 'String'>
  readonly level: Prisma.FieldRef<"AcademicClass", 'String'>
  readonly displayName: Prisma.FieldRef<"AcademicClass", 'String'>
  readonly position: Prisma.FieldRef<"AcademicClass", 'Int'>
  readonly isActive: Prisma.FieldRef<"AcademicClass", 'Boolean'>
  readonly createdAt: Prisma.FieldRef<"AcademicClass", 'DateTime'>
  readonly updatedAt: Prisma.FieldRef<"AcademicClass", 'DateTime'>
}
    

// Custom InputTypes
/**
 * AcademicClass findUnique
 */
export type AcademicClassFindUniqueArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the AcademicClass
   */
  select?: Prisma.AcademicClassSelect<ExtArgs> | null
  /**
   * Omit specific fields from the AcademicClass
   */
  omit?: Prisma.AcademicClassOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.AcademicClassInclude<ExtArgs> | null
  /**
   * Filter, which AcademicClass to fetch.
   */
  where: Prisma.AcademicClassWhereUniqueInput
}

/**
 * AcademicClass findUniqueOrThrow
 */
export type AcademicClassFindUniqueOrThrowArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the AcademicClass
   */
  select?: Prisma.AcademicClassSelect<ExtArgs> | null
  /**
   * Omit specific fields from the AcademicClass
   */
  omit?: Prisma.AcademicClassOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.AcademicClassInclude<ExtArgs> | null
  /**
   * Filter, which AcademicClass to fetch.
   */
  where: Prisma.AcademicClassWhereUniqueInput
}

/**
 * AcademicClass findFirst
 */
export type AcademicClassFindFirstArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the AcademicClass
   */
  select?: Prisma.AcademicClassSelect<ExtArgs> | null
  /**
   * Omit specific fields from the AcademicClass
   */
  omit?: Prisma.AcademicClassOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.AcademicClassInclude<ExtArgs> | null
  /**
   * Filter, which AcademicClass to fetch.
   */
  where?: Prisma.AcademicClassWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of AcademicClasses to fetch.
   */
  orderBy?: Prisma.AcademicClassOrderByWithRelationInput | Prisma.AcademicClassOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for searching for AcademicClasses.
   */
  cursor?: Prisma.AcademicClassWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` AcademicClasses from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` AcademicClasses.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of AcademicClasses.
   */
  distinct?: Prisma.AcademicClassScalarFieldEnum | Prisma.AcademicClassScalarFieldEnum[]
}

/**
 * AcademicClass findFirstOrThrow
 */
export type AcademicClassFindFirstOrThrowArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the AcademicClass
   */
  select?: Prisma.AcademicClassSelect<ExtArgs> | null
  /**
   * Omit specific fields from the AcademicClass
   */
  omit?: Prisma.AcademicClassOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.AcademicClassInclude<ExtArgs> | null
  /**
   * Filter, which AcademicClass to fetch.
   */
  where?: Prisma.AcademicClassWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of AcademicClasses to fetch.
   */
  orderBy?: Prisma.AcademicClassOrderByWithRelationInput | Prisma.AcademicClassOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for searching for AcademicClasses.
   */
  cursor?: Prisma.AcademicClassWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` AcademicClasses from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` AcademicClasses.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of AcademicClasses.
   */
  distinct?: Prisma.AcademicClassScalarFieldEnum | Prisma.AcademicClassScalarFieldEnum[]
}

/**
 * AcademicClass findMany
 */
export type AcademicClassFindManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the AcademicClass
   */
  select?: Prisma.AcademicClassSelect<ExtArgs> | null
  /**
   * Omit specific fields from the AcademicClass
   */
  omit?: Prisma.AcademicClassOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.AcademicClassInclude<ExtArgs> | null
  /**
   * Filter, which AcademicClasses to fetch.
   */
  where?: Prisma.AcademicClassWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of AcademicClasses to fetch.
   */
  orderBy?: Prisma.AcademicClassOrderByWithRelationInput | Prisma.AcademicClassOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for listing AcademicClasses.
   */
  cursor?: Prisma.AcademicClassWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` AcademicClasses from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` AcademicClasses.
   */
  skip?: number
  distinct?: Prisma.AcademicClassScalarFieldEnum | Prisma.AcademicClassScalarFieldEnum[]
}

/**
 * AcademicClass create
 */
export type AcademicClassCreateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the AcademicClass
   */
  select?: Prisma.AcademicClassSelect<ExtArgs> | null
  /**
   * Omit specific fields from the AcademicClass
   */
  omit?: Prisma.AcademicClassOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.AcademicClassInclude<ExtArgs> | null
  /**
   * The data needed to create a AcademicClass.
   */
  data: Prisma.XOR<Prisma.AcademicClassCreateInput, Prisma.AcademicClassUncheckedCreateInput>
}

/**
 * AcademicClass createMany
 */
export type AcademicClassCreateManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * The data used to create many AcademicClasses.
   */
  data: Prisma.AcademicClassCreateManyInput | Prisma.AcademicClassCreateManyInput[]
  skipDuplicates?: boolean
}

/**
 * AcademicClass createManyAndReturn
 */
export type AcademicClassCreateManyAndReturnArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the AcademicClass
   */
  select?: Prisma.AcademicClassSelectCreateManyAndReturn<ExtArgs> | null
  /**
   * Omit specific fields from the AcademicClass
   */
  omit?: Prisma.AcademicClassOmit<ExtArgs> | null
  /**
   * The data used to create many AcademicClasses.
   */
  data: Prisma.AcademicClassCreateManyInput | Prisma.AcademicClassCreateManyInput[]
  skipDuplicates?: boolean
}

/**
 * AcademicClass update
 */
export type AcademicClassUpdateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the AcademicClass
   */
  select?: Prisma.AcademicClassSelect<ExtArgs> | null
  /**
   * Omit specific fields from the AcademicClass
   */
  omit?: Prisma.AcademicClassOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.AcademicClassInclude<ExtArgs> | null
  /**
   * The data needed to update a AcademicClass.
   */
  data: Prisma.XOR<Prisma.AcademicClassUpdateInput, Prisma.AcademicClassUncheckedUpdateInput>
  /**
   * Choose, which AcademicClass to update.
   */
  where: Prisma.AcademicClassWhereUniqueInput
}

/**
 * AcademicClass updateMany
 */
export type AcademicClassUpdateManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * The data used to update AcademicClasses.
   */
  data: Prisma.XOR<Prisma.AcademicClassUpdateManyMutationInput, Prisma.AcademicClassUncheckedUpdateManyInput>
  /**
   * Filter which AcademicClasses to update
   */
  where?: Prisma.AcademicClassWhereInput
  /**
   * Limit how many AcademicClasses to update.
   */
  limit?: number
}

/**
 * AcademicClass updateManyAndReturn
 */
export type AcademicClassUpdateManyAndReturnArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the AcademicClass
   */
  select?: Prisma.AcademicClassSelectUpdateManyAndReturn<ExtArgs> | null
  /**
   * Omit specific fields from the AcademicClass
   */
  omit?: Prisma.AcademicClassOmit<ExtArgs> | null
  /**
   * The data used to update AcademicClasses.
   */
  data: Prisma.XOR<Prisma.AcademicClassUpdateManyMutationInput, Prisma.AcademicClassUncheckedUpdateManyInput>
  /**
   * Filter which AcademicClasses to update
   */
  where?: Prisma.AcademicClassWhereInput
  /**
   * Limit how many AcademicClasses to update.
   */
  limit?: number
}

/**
 * AcademicClass upsert
 */
export type AcademicClassUpsertArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the AcademicClass
   */
  select?: Prisma.AcademicClassSelect<ExtArgs> | null
  /**
   * Omit specific fields from the AcademicClass
   */
  omit?: Prisma.AcademicClassOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.AcademicClassInclude<ExtArgs> | null
  /**
   * The filter to search for the AcademicClass to update in case it exists.
   */
  where: Prisma.AcademicClassWhereUniqueInput
  /**
   * In case the AcademicClass found by the `where` argument doesn't exist, create a new AcademicClass with this data.
   */
  create: Prisma.XOR<Prisma.AcademicClassCreateInput, Prisma.AcademicClassUncheckedCreateInput>
  /**
   * In case the AcademicClass was found with the provided `where` argument, update it with this data.
   */
  update: Prisma.XOR<Prisma.AcademicClassUpdateInput, Prisma.AcademicClassUncheckedUpdateInput>
}

/**
 * AcademicClass delete
 */
export type AcademicClassDeleteArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the AcademicClass
   */
  select?: Prisma.AcademicClassSelect<ExtArgs> | null
  /**
   * Omit specific fields from the AcademicClass
   */
  omit?: Prisma.AcademicClassOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.AcademicClassInclude<ExtArgs> | null
  /**
   * Filter which AcademicClass to delete.
   */
  where: Prisma.AcademicClassWhereUniqueInput
}

/**
 * AcademicClass deleteMany
 */
export type AcademicClassDeleteManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Filter which AcademicClasses to delete
   */
  where?: Prisma.AcademicClassWhereInput
  /**
   * Limit how many AcademicClasses to delete.
   */
  limit?: number
}

/**
 * AcademicClass.subjects
 */
export type AcademicClass$subjectsArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the AcademicSubject
   */
  select?: Prisma.AcademicSubjectSelect<ExtArgs> | null
  /**
   * Omit specific fields from the AcademicSubject
   */
  omit?: Prisma.AcademicSubjectOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.AcademicSubjectInclude<ExtArgs> | null
  where?: Prisma.AcademicSubjectWhereInput
  orderBy?: Prisma.AcademicSubjectOrderByWithRelationInput | Prisma.AcademicSubjectOrderByWithRelationInput[]
  cursor?: Prisma.AcademicSubjectWhereUniqueInput
  take?: number
  skip?: number
  distinct?: Prisma.AcademicSubjectScalarFieldEnum | Prisma.AcademicSubjectScalarFieldEnum[]
}

/**
 * AcademicClass.cqs
 */
export type AcademicClass$cqsArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Cq
   */
  select?: Prisma.CqSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Cq
   */
  omit?: Prisma.CqOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.CqInclude<ExtArgs> | null
  where?: Prisma.CqWhereInput
  orderBy?: Prisma.CqOrderByWithRelationInput | Prisma.CqOrderByWithRelationInput[]
  cursor?: Prisma.CqWhereUniqueInput
  take?: number
  skip?: number
  distinct?: Prisma.CqScalarFieldEnum | Prisma.CqScalarFieldEnum[]
}

/**
 * AcademicClass without action
 */
export type AcademicClassDefaultArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the AcademicClass
   */
  select?: Prisma.AcademicClassSelect<ExtArgs> | null
  /**
   * Omit specific fields from the AcademicClass
   */
  omit?: Prisma.AcademicClassOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.AcademicClassInclude<ExtArgs> | null
}
