
/* !!! This is code generated by Prisma. Do not edit directly. !!! */
/* eslint-disable */
// biome-ignore-all lint: generated file
// @ts-nocheck 
/*
 * This file exports the `Cq` model and its related types.
 *
 * 🟢 You can import this file directly.
 */
import type * as runtime from "@prisma/client/runtime/client"
import type * as $Enums from "../enums"
import type * as Prisma from "../internal/prismaNamespace"

/**
 * Model Cq
 * 
 */
export type CqModel = runtime.Types.Result.DefaultSelection<Prisma.$CqPayload>

export type AggregateCq = {
  _count: CqCountAggregateOutputType | null
  _avg: CqAvgAggregateOutputType | null
  _sum: CqSumAggregateOutputType | null
  _min: CqMinAggregateOutputType | null
  _max: CqMaxAggregateOutputType | null
}

export type CqAvgAggregateOutputType = {
  marks: number | null
}

export type CqSumAggregateOutputType = {
  marks: number | null
}

export type CqMinAggregateOutputType = {
  id: string | null
  questionA: string | null
  questionB: string | null
  questionC: string | null
  questionD: string | null
  context: string | null
  marks: number | null
  isActive: boolean | null
  classId: string | null
  subjectId: string | null
  chapterId: string | null
  topicId: string | null
  subTopicId: string | null
  createdAt: Date | null
  updatedAt: Date | null
}

export type CqMaxAggregateOutputType = {
  id: string | null
  questionA: string | null
  questionB: string | null
  questionC: string | null
  questionD: string | null
  context: string | null
  marks: number | null
  isActive: boolean | null
  classId: string | null
  subjectId: string | null
  chapterId: string | null
  topicId: string | null
  subTopicId: string | null
  createdAt: Date | null
  updatedAt: Date | null
}

export type CqCountAggregateOutputType = {
  id: number
  questionA: number
  questionB: number
  questionC: number
  questionD: number
  context: number
  marks: number
  isActive: number
  classId: number
  subjectId: number
  chapterId: number
  topicId: number
  subTopicId: number
  createdAt: number
  updatedAt: number
  _all: number
}


export type CqAvgAggregateInputType = {
  marks?: true
}

export type CqSumAggregateInputType = {
  marks?: true
}

export type CqMinAggregateInputType = {
  id?: true
  questionA?: true
  questionB?: true
  questionC?: true
  questionD?: true
  context?: true
  marks?: true
  isActive?: true
  classId?: true
  subjectId?: true
  chapterId?: true
  topicId?: true
  subTopicId?: true
  createdAt?: true
  updatedAt?: true
}

export type CqMaxAggregateInputType = {
  id?: true
  questionA?: true
  questionB?: true
  questionC?: true
  questionD?: true
  context?: true
  marks?: true
  isActive?: true
  classId?: true
  subjectId?: true
  chapterId?: true
  topicId?: true
  subTopicId?: true
  createdAt?: true
  updatedAt?: true
}

export type CqCountAggregateInputType = {
  id?: true
  questionA?: true
  questionB?: true
  questionC?: true
  questionD?: true
  context?: true
  marks?: true
  isActive?: true
  classId?: true
  subjectId?: true
  chapterId?: true
  topicId?: true
  subTopicId?: true
  createdAt?: true
  updatedAt?: true
  _all?: true
}

export type CqAggregateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Filter which Cq to aggregate.
   */
  where?: Prisma.CqWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of Cqs to fetch.
   */
  orderBy?: Prisma.CqOrderByWithRelationInput | Prisma.CqOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the start position
   */
  cursor?: Prisma.CqWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` Cqs from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` Cqs.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Count returned Cqs
  **/
  _count?: true | CqCountAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to average
  **/
  _avg?: CqAvgAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to sum
  **/
  _sum?: CqSumAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to find the minimum value
  **/
  _min?: CqMinAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to find the maximum value
  **/
  _max?: CqMaxAggregateInputType
}

export type GetCqAggregateType<T extends CqAggregateArgs> = {
      [P in keyof T & keyof AggregateCq]: P extends '_count' | 'count'
    ? T[P] extends true
      ? number
      : Prisma.GetScalarType<T[P], AggregateCq[P]>
    : Prisma.GetScalarType<T[P], AggregateCq[P]>
}




export type CqGroupByArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  where?: Prisma.CqWhereInput
  orderBy?: Prisma.CqOrderByWithAggregationInput | Prisma.CqOrderByWithAggregationInput[]
  by: Prisma.CqScalarFieldEnum[] | Prisma.CqScalarFieldEnum
  having?: Prisma.CqScalarWhereWithAggregatesInput
  take?: number
  skip?: number
  _count?: CqCountAggregateInputType | true
  _avg?: CqAvgAggregateInputType
  _sum?: CqSumAggregateInputType
  _min?: CqMinAggregateInputType
  _max?: CqMaxAggregateInputType
}

export type CqGroupByOutputType = {
  id: string
  questionA: string
  questionB: string
  questionC: string
  questionD: string
  context: string | null
  marks: number
  isActive: boolean
  classId: string
  subjectId: string
  chapterId: string
  topicId: string | null
  subTopicId: string | null
  createdAt: Date
  updatedAt: Date
  _count: CqCountAggregateOutputType | null
  _avg: CqAvgAggregateOutputType | null
  _sum: CqSumAggregateOutputType | null
  _min: CqMinAggregateOutputType | null
  _max: CqMaxAggregateOutputType | null
}

type GetCqGroupByPayload<T extends CqGroupByArgs> = Prisma.PrismaPromise<
  Array<
    Prisma.PickEnumerable<CqGroupByOutputType, T['by']> &
      {
        [P in ((keyof T) & (keyof CqGroupByOutputType))]: P extends '_count'
          ? T[P] extends boolean
            ? number
            : Prisma.GetScalarType<T[P], CqGroupByOutputType[P]>
          : Prisma.GetScalarType<T[P], CqGroupByOutputType[P]>
      }
    >
  >



export type CqWhereInput = {
  AND?: Prisma.CqWhereInput | Prisma.CqWhereInput[]
  OR?: Prisma.CqWhereInput[]
  NOT?: Prisma.CqWhereInput | Prisma.CqWhereInput[]
  id?: Prisma.StringFilter<"Cq"> | string
  questionA?: Prisma.StringFilter<"Cq"> | string
  questionB?: Prisma.StringFilter<"Cq"> | string
  questionC?: Prisma.StringFilter<"Cq"> | string
  questionD?: Prisma.StringFilter<"Cq"> | string
  context?: Prisma.StringNullableFilter<"Cq"> | string | null
  marks?: Prisma.FloatFilter<"Cq"> | number
  isActive?: Prisma.BoolFilter<"Cq"> | boolean
  classId?: Prisma.StringFilter<"Cq"> | string
  subjectId?: Prisma.StringFilter<"Cq"> | string
  chapterId?: Prisma.StringFilter<"Cq"> | string
  topicId?: Prisma.StringNullableFilter<"Cq"> | string | null
  subTopicId?: Prisma.StringNullableFilter<"Cq"> | string | null
  createdAt?: Prisma.DateTimeFilter<"Cq"> | Date | string
  updatedAt?: Prisma.DateTimeFilter<"Cq"> | Date | string
  class?: Prisma.XOR<Prisma.AcademicClassScalarRelationFilter, Prisma.AcademicClassWhereInput>
  subject?: Prisma.XOR<Prisma.AcademicSubjectScalarRelationFilter, Prisma.AcademicSubjectWhereInput>
  chapter?: Prisma.XOR<Prisma.AcademicChapterScalarRelationFilter, Prisma.AcademicChapterWhereInput>
  topic?: Prisma.XOR<Prisma.AcademicTopicNullableScalarRelationFilter, Prisma.AcademicTopicWhereInput> | null
  subtopic?: Prisma.XOR<Prisma.AcademicSubTopicNullableScalarRelationFilter, Prisma.AcademicSubTopicWhereInput> | null
}

export type CqOrderByWithRelationInput = {
  id?: Prisma.SortOrder
  questionA?: Prisma.SortOrder
  questionB?: Prisma.SortOrder
  questionC?: Prisma.SortOrder
  questionD?: Prisma.SortOrder
  context?: Prisma.SortOrderInput | Prisma.SortOrder
  marks?: Prisma.SortOrder
  isActive?: Prisma.SortOrder
  classId?: Prisma.SortOrder
  subjectId?: Prisma.SortOrder
  chapterId?: Prisma.SortOrder
  topicId?: Prisma.SortOrderInput | Prisma.SortOrder
  subTopicId?: Prisma.SortOrderInput | Prisma.SortOrder
  createdAt?: Prisma.SortOrder
  updatedAt?: Prisma.SortOrder
  class?: Prisma.AcademicClassOrderByWithRelationInput
  subject?: Prisma.AcademicSubjectOrderByWithRelationInput
  chapter?: Prisma.AcademicChapterOrderByWithRelationInput
  topic?: Prisma.AcademicTopicOrderByWithRelationInput
  subtopic?: Prisma.AcademicSubTopicOrderByWithRelationInput
}

export type CqWhereUniqueInput = Prisma.AtLeast<{
  id?: string
  AND?: Prisma.CqWhereInput | Prisma.CqWhereInput[]
  OR?: Prisma.CqWhereInput[]
  NOT?: Prisma.CqWhereInput | Prisma.CqWhereInput[]
  questionA?: Prisma.StringFilter<"Cq"> | string
  questionB?: Prisma.StringFilter<"Cq"> | string
  questionC?: Prisma.StringFilter<"Cq"> | string
  questionD?: Prisma.StringFilter<"Cq"> | string
  context?: Prisma.StringNullableFilter<"Cq"> | string | null
  marks?: Prisma.FloatFilter<"Cq"> | number
  isActive?: Prisma.BoolFilter<"Cq"> | boolean
  classId?: Prisma.StringFilter<"Cq"> | string
  subjectId?: Prisma.StringFilter<"Cq"> | string
  chapterId?: Prisma.StringFilter<"Cq"> | string
  topicId?: Prisma.StringNullableFilter<"Cq"> | string | null
  subTopicId?: Prisma.StringNullableFilter<"Cq"> | string | null
  createdAt?: Prisma.DateTimeFilter<"Cq"> | Date | string
  updatedAt?: Prisma.DateTimeFilter<"Cq"> | Date | string
  class?: Prisma.XOR<Prisma.AcademicClassScalarRelationFilter, Prisma.AcademicClassWhereInput>
  subject?: Prisma.XOR<Prisma.AcademicSubjectScalarRelationFilter, Prisma.AcademicSubjectWhereInput>
  chapter?: Prisma.XOR<Prisma.AcademicChapterScalarRelationFilter, Prisma.AcademicChapterWhereInput>
  topic?: Prisma.XOR<Prisma.AcademicTopicNullableScalarRelationFilter, Prisma.AcademicTopicWhereInput> | null
  subtopic?: Prisma.XOR<Prisma.AcademicSubTopicNullableScalarRelationFilter, Prisma.AcademicSubTopicWhereInput> | null
}, "id">

export type CqOrderByWithAggregationInput = {
  id?: Prisma.SortOrder
  questionA?: Prisma.SortOrder
  questionB?: Prisma.SortOrder
  questionC?: Prisma.SortOrder
  questionD?: Prisma.SortOrder
  context?: Prisma.SortOrderInput | Prisma.SortOrder
  marks?: Prisma.SortOrder
  isActive?: Prisma.SortOrder
  classId?: Prisma.SortOrder
  subjectId?: Prisma.SortOrder
  chapterId?: Prisma.SortOrder
  topicId?: Prisma.SortOrderInput | Prisma.SortOrder
  subTopicId?: Prisma.SortOrderInput | Prisma.SortOrder
  createdAt?: Prisma.SortOrder
  updatedAt?: Prisma.SortOrder
  _count?: Prisma.CqCountOrderByAggregateInput
  _avg?: Prisma.CqAvgOrderByAggregateInput
  _max?: Prisma.CqMaxOrderByAggregateInput
  _min?: Prisma.CqMinOrderByAggregateInput
  _sum?: Prisma.CqSumOrderByAggregateInput
}

export type CqScalarWhereWithAggregatesInput = {
  AND?: Prisma.CqScalarWhereWithAggregatesInput | Prisma.CqScalarWhereWithAggregatesInput[]
  OR?: Prisma.CqScalarWhereWithAggregatesInput[]
  NOT?: Prisma.CqScalarWhereWithAggregatesInput | Prisma.CqScalarWhereWithAggregatesInput[]
  id?: Prisma.StringWithAggregatesFilter<"Cq"> | string
  questionA?: Prisma.StringWithAggregatesFilter<"Cq"> | string
  questionB?: Prisma.StringWithAggregatesFilter<"Cq"> | string
  questionC?: Prisma.StringWithAggregatesFilter<"Cq"> | string
  questionD?: Prisma.StringWithAggregatesFilter<"Cq"> | string
  context?: Prisma.StringNullableWithAggregatesFilter<"Cq"> | string | null
  marks?: Prisma.FloatWithAggregatesFilter<"Cq"> | number
  isActive?: Prisma.BoolWithAggregatesFilter<"Cq"> | boolean
  classId?: Prisma.StringWithAggregatesFilter<"Cq"> | string
  subjectId?: Prisma.StringWithAggregatesFilter<"Cq"> | string
  chapterId?: Prisma.StringWithAggregatesFilter<"Cq"> | string
  topicId?: Prisma.StringNullableWithAggregatesFilter<"Cq"> | string | null
  subTopicId?: Prisma.StringNullableWithAggregatesFilter<"Cq"> | string | null
  createdAt?: Prisma.DateTimeWithAggregatesFilter<"Cq"> | Date | string
  updatedAt?: Prisma.DateTimeWithAggregatesFilter<"Cq"> | Date | string
}

export type CqCreateInput = {
  id?: string
  questionA: string
  questionB: string
  questionC: string
  questionD: string
  context?: string | null
  marks?: number
  isActive?: boolean
  createdAt?: Date | string
  updatedAt?: Date | string
  class: Prisma.AcademicClassCreateNestedOneWithoutCqsInput
  subject: Prisma.AcademicSubjectCreateNestedOneWithoutCqsInput
  chapter: Prisma.AcademicChapterCreateNestedOneWithoutCqsInput
  topic?: Prisma.AcademicTopicCreateNestedOneWithoutCqsInput
  subtopic?: Prisma.AcademicSubTopicCreateNestedOneWithoutCqsInput
}

export type CqUncheckedCreateInput = {
  id?: string
  questionA: string
  questionB: string
  questionC: string
  questionD: string
  context?: string | null
  marks?: number
  isActive?: boolean
  classId: string
  subjectId: string
  chapterId: string
  topicId?: string | null
  subTopicId?: string | null
  createdAt?: Date | string
  updatedAt?: Date | string
}

export type CqUpdateInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  questionA?: Prisma.StringFieldUpdateOperationsInput | string
  questionB?: Prisma.StringFieldUpdateOperationsInput | string
  questionC?: Prisma.StringFieldUpdateOperationsInput | string
  questionD?: Prisma.StringFieldUpdateOperationsInput | string
  context?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  marks?: Prisma.FloatFieldUpdateOperationsInput | number
  isActive?: Prisma.BoolFieldUpdateOperationsInput | boolean
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  class?: Prisma.AcademicClassUpdateOneRequiredWithoutCqsNestedInput
  subject?: Prisma.AcademicSubjectUpdateOneRequiredWithoutCqsNestedInput
  chapter?: Prisma.AcademicChapterUpdateOneRequiredWithoutCqsNestedInput
  topic?: Prisma.AcademicTopicUpdateOneWithoutCqsNestedInput
  subtopic?: Prisma.AcademicSubTopicUpdateOneWithoutCqsNestedInput
}

export type CqUncheckedUpdateInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  questionA?: Prisma.StringFieldUpdateOperationsInput | string
  questionB?: Prisma.StringFieldUpdateOperationsInput | string
  questionC?: Prisma.StringFieldUpdateOperationsInput | string
  questionD?: Prisma.StringFieldUpdateOperationsInput | string
  context?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  marks?: Prisma.FloatFieldUpdateOperationsInput | number
  isActive?: Prisma.BoolFieldUpdateOperationsInput | boolean
  classId?: Prisma.StringFieldUpdateOperationsInput | string
  subjectId?: Prisma.StringFieldUpdateOperationsInput | string
  chapterId?: Prisma.StringFieldUpdateOperationsInput | string
  topicId?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  subTopicId?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type CqCreateManyInput = {
  id?: string
  questionA: string
  questionB: string
  questionC: string
  questionD: string
  context?: string | null
  marks?: number
  isActive?: boolean
  classId: string
  subjectId: string
  chapterId: string
  topicId?: string | null
  subTopicId?: string | null
  createdAt?: Date | string
  updatedAt?: Date | string
}

export type CqUpdateManyMutationInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  questionA?: Prisma.StringFieldUpdateOperationsInput | string
  questionB?: Prisma.StringFieldUpdateOperationsInput | string
  questionC?: Prisma.StringFieldUpdateOperationsInput | string
  questionD?: Prisma.StringFieldUpdateOperationsInput | string
  context?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  marks?: Prisma.FloatFieldUpdateOperationsInput | number
  isActive?: Prisma.BoolFieldUpdateOperationsInput | boolean
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type CqUncheckedUpdateManyInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  questionA?: Prisma.StringFieldUpdateOperationsInput | string
  questionB?: Prisma.StringFieldUpdateOperationsInput | string
  questionC?: Prisma.StringFieldUpdateOperationsInput | string
  questionD?: Prisma.StringFieldUpdateOperationsInput | string
  context?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  marks?: Prisma.FloatFieldUpdateOperationsInput | number
  isActive?: Prisma.BoolFieldUpdateOperationsInput | boolean
  classId?: Prisma.StringFieldUpdateOperationsInput | string
  subjectId?: Prisma.StringFieldUpdateOperationsInput | string
  chapterId?: Prisma.StringFieldUpdateOperationsInput | string
  topicId?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  subTopicId?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type CqListRelationFilter = {
  every?: Prisma.CqWhereInput
  some?: Prisma.CqWhereInput
  none?: Prisma.CqWhereInput
}

export type CqOrderByRelationAggregateInput = {
  _count?: Prisma.SortOrder
}

export type CqCountOrderByAggregateInput = {
  id?: Prisma.SortOrder
  questionA?: Prisma.SortOrder
  questionB?: Prisma.SortOrder
  questionC?: Prisma.SortOrder
  questionD?: Prisma.SortOrder
  context?: Prisma.SortOrder
  marks?: Prisma.SortOrder
  isActive?: Prisma.SortOrder
  classId?: Prisma.SortOrder
  subjectId?: Prisma.SortOrder
  chapterId?: Prisma.SortOrder
  topicId?: Prisma.SortOrder
  subTopicId?: Prisma.SortOrder
  createdAt?: Prisma.SortOrder
  updatedAt?: Prisma.SortOrder
}

export type CqAvgOrderByAggregateInput = {
  marks?: Prisma.SortOrder
}

export type CqMaxOrderByAggregateInput = {
  id?: Prisma.SortOrder
  questionA?: Prisma.SortOrder
  questionB?: Prisma.SortOrder
  questionC?: Prisma.SortOrder
  questionD?: Prisma.SortOrder
  context?: Prisma.SortOrder
  marks?: Prisma.SortOrder
  isActive?: Prisma.SortOrder
  classId?: Prisma.SortOrder
  subjectId?: Prisma.SortOrder
  chapterId?: Prisma.SortOrder
  topicId?: Prisma.SortOrder
  subTopicId?: Prisma.SortOrder
  createdAt?: Prisma.SortOrder
  updatedAt?: Prisma.SortOrder
}

export type CqMinOrderByAggregateInput = {
  id?: Prisma.SortOrder
  questionA?: Prisma.SortOrder
  questionB?: Prisma.SortOrder
  questionC?: Prisma.SortOrder
  questionD?: Prisma.SortOrder
  context?: Prisma.SortOrder
  marks?: Prisma.SortOrder
  isActive?: Prisma.SortOrder
  classId?: Prisma.SortOrder
  subjectId?: Prisma.SortOrder
  chapterId?: Prisma.SortOrder
  topicId?: Prisma.SortOrder
  subTopicId?: Prisma.SortOrder
  createdAt?: Prisma.SortOrder
  updatedAt?: Prisma.SortOrder
}

export type CqSumOrderByAggregateInput = {
  marks?: Prisma.SortOrder
}

export type CqCreateNestedManyWithoutClassInput = {
  create?: Prisma.XOR<Prisma.CqCreateWithoutClassInput, Prisma.CqUncheckedCreateWithoutClassInput> | Prisma.CqCreateWithoutClassInput[] | Prisma.CqUncheckedCreateWithoutClassInput[]
  connectOrCreate?: Prisma.CqCreateOrConnectWithoutClassInput | Prisma.CqCreateOrConnectWithoutClassInput[]
  createMany?: Prisma.CqCreateManyClassInputEnvelope
  connect?: Prisma.CqWhereUniqueInput | Prisma.CqWhereUniqueInput[]
}

export type CqUncheckedCreateNestedManyWithoutClassInput = {
  create?: Prisma.XOR<Prisma.CqCreateWithoutClassInput, Prisma.CqUncheckedCreateWithoutClassInput> | Prisma.CqCreateWithoutClassInput[] | Prisma.CqUncheckedCreateWithoutClassInput[]
  connectOrCreate?: Prisma.CqCreateOrConnectWithoutClassInput | Prisma.CqCreateOrConnectWithoutClassInput[]
  createMany?: Prisma.CqCreateManyClassInputEnvelope
  connect?: Prisma.CqWhereUniqueInput | Prisma.CqWhereUniqueInput[]
}

export type CqUpdateManyWithoutClassNestedInput = {
  create?: Prisma.XOR<Prisma.CqCreateWithoutClassInput, Prisma.CqUncheckedCreateWithoutClassInput> | Prisma.CqCreateWithoutClassInput[] | Prisma.CqUncheckedCreateWithoutClassInput[]
  connectOrCreate?: Prisma.CqCreateOrConnectWithoutClassInput | Prisma.CqCreateOrConnectWithoutClassInput[]
  upsert?: Prisma.CqUpsertWithWhereUniqueWithoutClassInput | Prisma.CqUpsertWithWhereUniqueWithoutClassInput[]
  createMany?: Prisma.CqCreateManyClassInputEnvelope
  set?: Prisma.CqWhereUniqueInput | Prisma.CqWhereUniqueInput[]
  disconnect?: Prisma.CqWhereUniqueInput | Prisma.CqWhereUniqueInput[]
  delete?: Prisma.CqWhereUniqueInput | Prisma.CqWhereUniqueInput[]
  connect?: Prisma.CqWhereUniqueInput | Prisma.CqWhereUniqueInput[]
  update?: Prisma.CqUpdateWithWhereUniqueWithoutClassInput | Prisma.CqUpdateWithWhereUniqueWithoutClassInput[]
  updateMany?: Prisma.CqUpdateManyWithWhereWithoutClassInput | Prisma.CqUpdateManyWithWhereWithoutClassInput[]
  deleteMany?: Prisma.CqScalarWhereInput | Prisma.CqScalarWhereInput[]
}

export type CqUncheckedUpdateManyWithoutClassNestedInput = {
  create?: Prisma.XOR<Prisma.CqCreateWithoutClassInput, Prisma.CqUncheckedCreateWithoutClassInput> | Prisma.CqCreateWithoutClassInput[] | Prisma.CqUncheckedCreateWithoutClassInput[]
  connectOrCreate?: Prisma.CqCreateOrConnectWithoutClassInput | Prisma.CqCreateOrConnectWithoutClassInput[]
  upsert?: Prisma.CqUpsertWithWhereUniqueWithoutClassInput | Prisma.CqUpsertWithWhereUniqueWithoutClassInput[]
  createMany?: Prisma.CqCreateManyClassInputEnvelope
  set?: Prisma.CqWhereUniqueInput | Prisma.CqWhereUniqueInput[]
  disconnect?: Prisma.CqWhereUniqueInput | Prisma.CqWhereUniqueInput[]
  delete?: Prisma.CqWhereUniqueInput | Prisma.CqWhereUniqueInput[]
  connect?: Prisma.CqWhereUniqueInput | Prisma.CqWhereUniqueInput[]
  update?: Prisma.CqUpdateWithWhereUniqueWithoutClassInput | Prisma.CqUpdateWithWhereUniqueWithoutClassInput[]
  updateMany?: Prisma.CqUpdateManyWithWhereWithoutClassInput | Prisma.CqUpdateManyWithWhereWithoutClassInput[]
  deleteMany?: Prisma.CqScalarWhereInput | Prisma.CqScalarWhereInput[]
}

export type CqCreateNestedManyWithoutSubjectInput = {
  create?: Prisma.XOR<Prisma.CqCreateWithoutSubjectInput, Prisma.CqUncheckedCreateWithoutSubjectInput> | Prisma.CqCreateWithoutSubjectInput[] | Prisma.CqUncheckedCreateWithoutSubjectInput[]
  connectOrCreate?: Prisma.CqCreateOrConnectWithoutSubjectInput | Prisma.CqCreateOrConnectWithoutSubjectInput[]
  createMany?: Prisma.CqCreateManySubjectInputEnvelope
  connect?: Prisma.CqWhereUniqueInput | Prisma.CqWhereUniqueInput[]
}

export type CqUncheckedCreateNestedManyWithoutSubjectInput = {
  create?: Prisma.XOR<Prisma.CqCreateWithoutSubjectInput, Prisma.CqUncheckedCreateWithoutSubjectInput> | Prisma.CqCreateWithoutSubjectInput[] | Prisma.CqUncheckedCreateWithoutSubjectInput[]
  connectOrCreate?: Prisma.CqCreateOrConnectWithoutSubjectInput | Prisma.CqCreateOrConnectWithoutSubjectInput[]
  createMany?: Prisma.CqCreateManySubjectInputEnvelope
  connect?: Prisma.CqWhereUniqueInput | Prisma.CqWhereUniqueInput[]
}

export type CqUpdateManyWithoutSubjectNestedInput = {
  create?: Prisma.XOR<Prisma.CqCreateWithoutSubjectInput, Prisma.CqUncheckedCreateWithoutSubjectInput> | Prisma.CqCreateWithoutSubjectInput[] | Prisma.CqUncheckedCreateWithoutSubjectInput[]
  connectOrCreate?: Prisma.CqCreateOrConnectWithoutSubjectInput | Prisma.CqCreateOrConnectWithoutSubjectInput[]
  upsert?: Prisma.CqUpsertWithWhereUniqueWithoutSubjectInput | Prisma.CqUpsertWithWhereUniqueWithoutSubjectInput[]
  createMany?: Prisma.CqCreateManySubjectInputEnvelope
  set?: Prisma.CqWhereUniqueInput | Prisma.CqWhereUniqueInput[]
  disconnect?: Prisma.CqWhereUniqueInput | Prisma.CqWhereUniqueInput[]
  delete?: Prisma.CqWhereUniqueInput | Prisma.CqWhereUniqueInput[]
  connect?: Prisma.CqWhereUniqueInput | Prisma.CqWhereUniqueInput[]
  update?: Prisma.CqUpdateWithWhereUniqueWithoutSubjectInput | Prisma.CqUpdateWithWhereUniqueWithoutSubjectInput[]
  updateMany?: Prisma.CqUpdateManyWithWhereWithoutSubjectInput | Prisma.CqUpdateManyWithWhereWithoutSubjectInput[]
  deleteMany?: Prisma.CqScalarWhereInput | Prisma.CqScalarWhereInput[]
}

export type CqUncheckedUpdateManyWithoutSubjectNestedInput = {
  create?: Prisma.XOR<Prisma.CqCreateWithoutSubjectInput, Prisma.CqUncheckedCreateWithoutSubjectInput> | Prisma.CqCreateWithoutSubjectInput[] | Prisma.CqUncheckedCreateWithoutSubjectInput[]
  connectOrCreate?: Prisma.CqCreateOrConnectWithoutSubjectInput | Prisma.CqCreateOrConnectWithoutSubjectInput[]
  upsert?: Prisma.CqUpsertWithWhereUniqueWithoutSubjectInput | Prisma.CqUpsertWithWhereUniqueWithoutSubjectInput[]
  createMany?: Prisma.CqCreateManySubjectInputEnvelope
  set?: Prisma.CqWhereUniqueInput | Prisma.CqWhereUniqueInput[]
  disconnect?: Prisma.CqWhereUniqueInput | Prisma.CqWhereUniqueInput[]
  delete?: Prisma.CqWhereUniqueInput | Prisma.CqWhereUniqueInput[]
  connect?: Prisma.CqWhereUniqueInput | Prisma.CqWhereUniqueInput[]
  update?: Prisma.CqUpdateWithWhereUniqueWithoutSubjectInput | Prisma.CqUpdateWithWhereUniqueWithoutSubjectInput[]
  updateMany?: Prisma.CqUpdateManyWithWhereWithoutSubjectInput | Prisma.CqUpdateManyWithWhereWithoutSubjectInput[]
  deleteMany?: Prisma.CqScalarWhereInput | Prisma.CqScalarWhereInput[]
}

export type CqCreateNestedManyWithoutChapterInput = {
  create?: Prisma.XOR<Prisma.CqCreateWithoutChapterInput, Prisma.CqUncheckedCreateWithoutChapterInput> | Prisma.CqCreateWithoutChapterInput[] | Prisma.CqUncheckedCreateWithoutChapterInput[]
  connectOrCreate?: Prisma.CqCreateOrConnectWithoutChapterInput | Prisma.CqCreateOrConnectWithoutChapterInput[]
  createMany?: Prisma.CqCreateManyChapterInputEnvelope
  connect?: Prisma.CqWhereUniqueInput | Prisma.CqWhereUniqueInput[]
}

export type CqUncheckedCreateNestedManyWithoutChapterInput = {
  create?: Prisma.XOR<Prisma.CqCreateWithoutChapterInput, Prisma.CqUncheckedCreateWithoutChapterInput> | Prisma.CqCreateWithoutChapterInput[] | Prisma.CqUncheckedCreateWithoutChapterInput[]
  connectOrCreate?: Prisma.CqCreateOrConnectWithoutChapterInput | Prisma.CqCreateOrConnectWithoutChapterInput[]
  createMany?: Prisma.CqCreateManyChapterInputEnvelope
  connect?: Prisma.CqWhereUniqueInput | Prisma.CqWhereUniqueInput[]
}

export type CqUpdateManyWithoutChapterNestedInput = {
  create?: Prisma.XOR<Prisma.CqCreateWithoutChapterInput, Prisma.CqUncheckedCreateWithoutChapterInput> | Prisma.CqCreateWithoutChapterInput[] | Prisma.CqUncheckedCreateWithoutChapterInput[]
  connectOrCreate?: Prisma.CqCreateOrConnectWithoutChapterInput | Prisma.CqCreateOrConnectWithoutChapterInput[]
  upsert?: Prisma.CqUpsertWithWhereUniqueWithoutChapterInput | Prisma.CqUpsertWithWhereUniqueWithoutChapterInput[]
  createMany?: Prisma.CqCreateManyChapterInputEnvelope
  set?: Prisma.CqWhereUniqueInput | Prisma.CqWhereUniqueInput[]
  disconnect?: Prisma.CqWhereUniqueInput | Prisma.CqWhereUniqueInput[]
  delete?: Prisma.CqWhereUniqueInput | Prisma.CqWhereUniqueInput[]
  connect?: Prisma.CqWhereUniqueInput | Prisma.CqWhereUniqueInput[]
  update?: Prisma.CqUpdateWithWhereUniqueWithoutChapterInput | Prisma.CqUpdateWithWhereUniqueWithoutChapterInput[]
  updateMany?: Prisma.CqUpdateManyWithWhereWithoutChapterInput | Prisma.CqUpdateManyWithWhereWithoutChapterInput[]
  deleteMany?: Prisma.CqScalarWhereInput | Prisma.CqScalarWhereInput[]
}

export type CqUncheckedUpdateManyWithoutChapterNestedInput = {
  create?: Prisma.XOR<Prisma.CqCreateWithoutChapterInput, Prisma.CqUncheckedCreateWithoutChapterInput> | Prisma.CqCreateWithoutChapterInput[] | Prisma.CqUncheckedCreateWithoutChapterInput[]
  connectOrCreate?: Prisma.CqCreateOrConnectWithoutChapterInput | Prisma.CqCreateOrConnectWithoutChapterInput[]
  upsert?: Prisma.CqUpsertWithWhereUniqueWithoutChapterInput | Prisma.CqUpsertWithWhereUniqueWithoutChapterInput[]
  createMany?: Prisma.CqCreateManyChapterInputEnvelope
  set?: Prisma.CqWhereUniqueInput | Prisma.CqWhereUniqueInput[]
  disconnect?: Prisma.CqWhereUniqueInput | Prisma.CqWhereUniqueInput[]
  delete?: Prisma.CqWhereUniqueInput | Prisma.CqWhereUniqueInput[]
  connect?: Prisma.CqWhereUniqueInput | Prisma.CqWhereUniqueInput[]
  update?: Prisma.CqUpdateWithWhereUniqueWithoutChapterInput | Prisma.CqUpdateWithWhereUniqueWithoutChapterInput[]
  updateMany?: Prisma.CqUpdateManyWithWhereWithoutChapterInput | Prisma.CqUpdateManyWithWhereWithoutChapterInput[]
  deleteMany?: Prisma.CqScalarWhereInput | Prisma.CqScalarWhereInput[]
}

export type CqCreateNestedManyWithoutTopicInput = {
  create?: Prisma.XOR<Prisma.CqCreateWithoutTopicInput, Prisma.CqUncheckedCreateWithoutTopicInput> | Prisma.CqCreateWithoutTopicInput[] | Prisma.CqUncheckedCreateWithoutTopicInput[]
  connectOrCreate?: Prisma.CqCreateOrConnectWithoutTopicInput | Prisma.CqCreateOrConnectWithoutTopicInput[]
  createMany?: Prisma.CqCreateManyTopicInputEnvelope
  connect?: Prisma.CqWhereUniqueInput | Prisma.CqWhereUniqueInput[]
}

export type CqUncheckedCreateNestedManyWithoutTopicInput = {
  create?: Prisma.XOR<Prisma.CqCreateWithoutTopicInput, Prisma.CqUncheckedCreateWithoutTopicInput> | Prisma.CqCreateWithoutTopicInput[] | Prisma.CqUncheckedCreateWithoutTopicInput[]
  connectOrCreate?: Prisma.CqCreateOrConnectWithoutTopicInput | Prisma.CqCreateOrConnectWithoutTopicInput[]
  createMany?: Prisma.CqCreateManyTopicInputEnvelope
  connect?: Prisma.CqWhereUniqueInput | Prisma.CqWhereUniqueInput[]
}

export type CqUpdateManyWithoutTopicNestedInput = {
  create?: Prisma.XOR<Prisma.CqCreateWithoutTopicInput, Prisma.CqUncheckedCreateWithoutTopicInput> | Prisma.CqCreateWithoutTopicInput[] | Prisma.CqUncheckedCreateWithoutTopicInput[]
  connectOrCreate?: Prisma.CqCreateOrConnectWithoutTopicInput | Prisma.CqCreateOrConnectWithoutTopicInput[]
  upsert?: Prisma.CqUpsertWithWhereUniqueWithoutTopicInput | Prisma.CqUpsertWithWhereUniqueWithoutTopicInput[]
  createMany?: Prisma.CqCreateManyTopicInputEnvelope
  set?: Prisma.CqWhereUniqueInput | Prisma.CqWhereUniqueInput[]
  disconnect?: Prisma.CqWhereUniqueInput | Prisma.CqWhereUniqueInput[]
  delete?: Prisma.CqWhereUniqueInput | Prisma.CqWhereUniqueInput[]
  connect?: Prisma.CqWhereUniqueInput | Prisma.CqWhereUniqueInput[]
  update?: Prisma.CqUpdateWithWhereUniqueWithoutTopicInput | Prisma.CqUpdateWithWhereUniqueWithoutTopicInput[]
  updateMany?: Prisma.CqUpdateManyWithWhereWithoutTopicInput | Prisma.CqUpdateManyWithWhereWithoutTopicInput[]
  deleteMany?: Prisma.CqScalarWhereInput | Prisma.CqScalarWhereInput[]
}

export type CqUncheckedUpdateManyWithoutTopicNestedInput = {
  create?: Prisma.XOR<Prisma.CqCreateWithoutTopicInput, Prisma.CqUncheckedCreateWithoutTopicInput> | Prisma.CqCreateWithoutTopicInput[] | Prisma.CqUncheckedCreateWithoutTopicInput[]
  connectOrCreate?: Prisma.CqCreateOrConnectWithoutTopicInput | Prisma.CqCreateOrConnectWithoutTopicInput[]
  upsert?: Prisma.CqUpsertWithWhereUniqueWithoutTopicInput | Prisma.CqUpsertWithWhereUniqueWithoutTopicInput[]
  createMany?: Prisma.CqCreateManyTopicInputEnvelope
  set?: Prisma.CqWhereUniqueInput | Prisma.CqWhereUniqueInput[]
  disconnect?: Prisma.CqWhereUniqueInput | Prisma.CqWhereUniqueInput[]
  delete?: Prisma.CqWhereUniqueInput | Prisma.CqWhereUniqueInput[]
  connect?: Prisma.CqWhereUniqueInput | Prisma.CqWhereUniqueInput[]
  update?: Prisma.CqUpdateWithWhereUniqueWithoutTopicInput | Prisma.CqUpdateWithWhereUniqueWithoutTopicInput[]
  updateMany?: Prisma.CqUpdateManyWithWhereWithoutTopicInput | Prisma.CqUpdateManyWithWhereWithoutTopicInput[]
  deleteMany?: Prisma.CqScalarWhereInput | Prisma.CqScalarWhereInput[]
}

export type CqCreateNestedManyWithoutSubtopicInput = {
  create?: Prisma.XOR<Prisma.CqCreateWithoutSubtopicInput, Prisma.CqUncheckedCreateWithoutSubtopicInput> | Prisma.CqCreateWithoutSubtopicInput[] | Prisma.CqUncheckedCreateWithoutSubtopicInput[]
  connectOrCreate?: Prisma.CqCreateOrConnectWithoutSubtopicInput | Prisma.CqCreateOrConnectWithoutSubtopicInput[]
  createMany?: Prisma.CqCreateManySubtopicInputEnvelope
  connect?: Prisma.CqWhereUniqueInput | Prisma.CqWhereUniqueInput[]
}

export type CqUncheckedCreateNestedManyWithoutSubtopicInput = {
  create?: Prisma.XOR<Prisma.CqCreateWithoutSubtopicInput, Prisma.CqUncheckedCreateWithoutSubtopicInput> | Prisma.CqCreateWithoutSubtopicInput[] | Prisma.CqUncheckedCreateWithoutSubtopicInput[]
  connectOrCreate?: Prisma.CqCreateOrConnectWithoutSubtopicInput | Prisma.CqCreateOrConnectWithoutSubtopicInput[]
  createMany?: Prisma.CqCreateManySubtopicInputEnvelope
  connect?: Prisma.CqWhereUniqueInput | Prisma.CqWhereUniqueInput[]
}

export type CqUpdateManyWithoutSubtopicNestedInput = {
  create?: Prisma.XOR<Prisma.CqCreateWithoutSubtopicInput, Prisma.CqUncheckedCreateWithoutSubtopicInput> | Prisma.CqCreateWithoutSubtopicInput[] | Prisma.CqUncheckedCreateWithoutSubtopicInput[]
  connectOrCreate?: Prisma.CqCreateOrConnectWithoutSubtopicInput | Prisma.CqCreateOrConnectWithoutSubtopicInput[]
  upsert?: Prisma.CqUpsertWithWhereUniqueWithoutSubtopicInput | Prisma.CqUpsertWithWhereUniqueWithoutSubtopicInput[]
  createMany?: Prisma.CqCreateManySubtopicInputEnvelope
  set?: Prisma.CqWhereUniqueInput | Prisma.CqWhereUniqueInput[]
  disconnect?: Prisma.CqWhereUniqueInput | Prisma.CqWhereUniqueInput[]
  delete?: Prisma.CqWhereUniqueInput | Prisma.CqWhereUniqueInput[]
  connect?: Prisma.CqWhereUniqueInput | Prisma.CqWhereUniqueInput[]
  update?: Prisma.CqUpdateWithWhereUniqueWithoutSubtopicInput | Prisma.CqUpdateWithWhereUniqueWithoutSubtopicInput[]
  updateMany?: Prisma.CqUpdateManyWithWhereWithoutSubtopicInput | Prisma.CqUpdateManyWithWhereWithoutSubtopicInput[]
  deleteMany?: Prisma.CqScalarWhereInput | Prisma.CqScalarWhereInput[]
}

export type CqUncheckedUpdateManyWithoutSubtopicNestedInput = {
  create?: Prisma.XOR<Prisma.CqCreateWithoutSubtopicInput, Prisma.CqUncheckedCreateWithoutSubtopicInput> | Prisma.CqCreateWithoutSubtopicInput[] | Prisma.CqUncheckedCreateWithoutSubtopicInput[]
  connectOrCreate?: Prisma.CqCreateOrConnectWithoutSubtopicInput | Prisma.CqCreateOrConnectWithoutSubtopicInput[]
  upsert?: Prisma.CqUpsertWithWhereUniqueWithoutSubtopicInput | Prisma.CqUpsertWithWhereUniqueWithoutSubtopicInput[]
  createMany?: Prisma.CqCreateManySubtopicInputEnvelope
  set?: Prisma.CqWhereUniqueInput | Prisma.CqWhereUniqueInput[]
  disconnect?: Prisma.CqWhereUniqueInput | Prisma.CqWhereUniqueInput[]
  delete?: Prisma.CqWhereUniqueInput | Prisma.CqWhereUniqueInput[]
  connect?: Prisma.CqWhereUniqueInput | Prisma.CqWhereUniqueInput[]
  update?: Prisma.CqUpdateWithWhereUniqueWithoutSubtopicInput | Prisma.CqUpdateWithWhereUniqueWithoutSubtopicInput[]
  updateMany?: Prisma.CqUpdateManyWithWhereWithoutSubtopicInput | Prisma.CqUpdateManyWithWhereWithoutSubtopicInput[]
  deleteMany?: Prisma.CqScalarWhereInput | Prisma.CqScalarWhereInput[]
}

export type FloatFieldUpdateOperationsInput = {
  set?: number
  increment?: number
  decrement?: number
  multiply?: number
  divide?: number
}

export type CqCreateWithoutClassInput = {
  id?: string
  questionA: string
  questionB: string
  questionC: string
  questionD: string
  context?: string | null
  marks?: number
  isActive?: boolean
  createdAt?: Date | string
  updatedAt?: Date | string
  subject: Prisma.AcademicSubjectCreateNestedOneWithoutCqsInput
  chapter: Prisma.AcademicChapterCreateNestedOneWithoutCqsInput
  topic?: Prisma.AcademicTopicCreateNestedOneWithoutCqsInput
  subtopic?: Prisma.AcademicSubTopicCreateNestedOneWithoutCqsInput
}

export type CqUncheckedCreateWithoutClassInput = {
  id?: string
  questionA: string
  questionB: string
  questionC: string
  questionD: string
  context?: string | null
  marks?: number
  isActive?: boolean
  subjectId: string
  chapterId: string
  topicId?: string | null
  subTopicId?: string | null
  createdAt?: Date | string
  updatedAt?: Date | string
}

export type CqCreateOrConnectWithoutClassInput = {
  where: Prisma.CqWhereUniqueInput
  create: Prisma.XOR<Prisma.CqCreateWithoutClassInput, Prisma.CqUncheckedCreateWithoutClassInput>
}

export type CqCreateManyClassInputEnvelope = {
  data: Prisma.CqCreateManyClassInput | Prisma.CqCreateManyClassInput[]
  skipDuplicates?: boolean
}

export type CqUpsertWithWhereUniqueWithoutClassInput = {
  where: Prisma.CqWhereUniqueInput
  update: Prisma.XOR<Prisma.CqUpdateWithoutClassInput, Prisma.CqUncheckedUpdateWithoutClassInput>
  create: Prisma.XOR<Prisma.CqCreateWithoutClassInput, Prisma.CqUncheckedCreateWithoutClassInput>
}

export type CqUpdateWithWhereUniqueWithoutClassInput = {
  where: Prisma.CqWhereUniqueInput
  data: Prisma.XOR<Prisma.CqUpdateWithoutClassInput, Prisma.CqUncheckedUpdateWithoutClassInput>
}

export type CqUpdateManyWithWhereWithoutClassInput = {
  where: Prisma.CqScalarWhereInput
  data: Prisma.XOR<Prisma.CqUpdateManyMutationInput, Prisma.CqUncheckedUpdateManyWithoutClassInput>
}

export type CqScalarWhereInput = {
  AND?: Prisma.CqScalarWhereInput | Prisma.CqScalarWhereInput[]
  OR?: Prisma.CqScalarWhereInput[]
  NOT?: Prisma.CqScalarWhereInput | Prisma.CqScalarWhereInput[]
  id?: Prisma.StringFilter<"Cq"> | string
  questionA?: Prisma.StringFilter<"Cq"> | string
  questionB?: Prisma.StringFilter<"Cq"> | string
  questionC?: Prisma.StringFilter<"Cq"> | string
  questionD?: Prisma.StringFilter<"Cq"> | string
  context?: Prisma.StringNullableFilter<"Cq"> | string | null
  marks?: Prisma.FloatFilter<"Cq"> | number
  isActive?: Prisma.BoolFilter<"Cq"> | boolean
  classId?: Prisma.StringFilter<"Cq"> | string
  subjectId?: Prisma.StringFilter<"Cq"> | string
  chapterId?: Prisma.StringFilter<"Cq"> | string
  topicId?: Prisma.StringNullableFilter<"Cq"> | string | null
  subTopicId?: Prisma.StringNullableFilter<"Cq"> | string | null
  createdAt?: Prisma.DateTimeFilter<"Cq"> | Date | string
  updatedAt?: Prisma.DateTimeFilter<"Cq"> | Date | string
}

export type CqCreateWithoutSubjectInput = {
  id?: string
  questionA: string
  questionB: string
  questionC: string
  questionD: string
  context?: string | null
  marks?: number
  isActive?: boolean
  createdAt?: Date | string
  updatedAt?: Date | string
  class: Prisma.AcademicClassCreateNestedOneWithoutCqsInput
  chapter: Prisma.AcademicChapterCreateNestedOneWithoutCqsInput
  topic?: Prisma.AcademicTopicCreateNestedOneWithoutCqsInput
  subtopic?: Prisma.AcademicSubTopicCreateNestedOneWithoutCqsInput
}

export type CqUncheckedCreateWithoutSubjectInput = {
  id?: string
  questionA: string
  questionB: string
  questionC: string
  questionD: string
  context?: string | null
  marks?: number
  isActive?: boolean
  classId: string
  chapterId: string
  topicId?: string | null
  subTopicId?: string | null
  createdAt?: Date | string
  updatedAt?: Date | string
}

export type CqCreateOrConnectWithoutSubjectInput = {
  where: Prisma.CqWhereUniqueInput
  create: Prisma.XOR<Prisma.CqCreateWithoutSubjectInput, Prisma.CqUncheckedCreateWithoutSubjectInput>
}

export type CqCreateManySubjectInputEnvelope = {
  data: Prisma.CqCreateManySubjectInput | Prisma.CqCreateManySubjectInput[]
  skipDuplicates?: boolean
}

export type CqUpsertWithWhereUniqueWithoutSubjectInput = {
  where: Prisma.CqWhereUniqueInput
  update: Prisma.XOR<Prisma.CqUpdateWithoutSubjectInput, Prisma.CqUncheckedUpdateWithoutSubjectInput>
  create: Prisma.XOR<Prisma.CqCreateWithoutSubjectInput, Prisma.CqUncheckedCreateWithoutSubjectInput>
}

export type CqUpdateWithWhereUniqueWithoutSubjectInput = {
  where: Prisma.CqWhereUniqueInput
  data: Prisma.XOR<Prisma.CqUpdateWithoutSubjectInput, Prisma.CqUncheckedUpdateWithoutSubjectInput>
}

export type CqUpdateManyWithWhereWithoutSubjectInput = {
  where: Prisma.CqScalarWhereInput
  data: Prisma.XOR<Prisma.CqUpdateManyMutationInput, Prisma.CqUncheckedUpdateManyWithoutSubjectInput>
}

export type CqCreateWithoutChapterInput = {
  id?: string
  questionA: string
  questionB: string
  questionC: string
  questionD: string
  context?: string | null
  marks?: number
  isActive?: boolean
  createdAt?: Date | string
  updatedAt?: Date | string
  class: Prisma.AcademicClassCreateNestedOneWithoutCqsInput
  subject: Prisma.AcademicSubjectCreateNestedOneWithoutCqsInput
  topic?: Prisma.AcademicTopicCreateNestedOneWithoutCqsInput
  subtopic?: Prisma.AcademicSubTopicCreateNestedOneWithoutCqsInput
}

export type CqUncheckedCreateWithoutChapterInput = {
  id?: string
  questionA: string
  questionB: string
  questionC: string
  questionD: string
  context?: string | null
  marks?: number
  isActive?: boolean
  classId: string
  subjectId: string
  topicId?: string | null
  subTopicId?: string | null
  createdAt?: Date | string
  updatedAt?: Date | string
}

export type CqCreateOrConnectWithoutChapterInput = {
  where: Prisma.CqWhereUniqueInput
  create: Prisma.XOR<Prisma.CqCreateWithoutChapterInput, Prisma.CqUncheckedCreateWithoutChapterInput>
}

export type CqCreateManyChapterInputEnvelope = {
  data: Prisma.CqCreateManyChapterInput | Prisma.CqCreateManyChapterInput[]
  skipDuplicates?: boolean
}

export type CqUpsertWithWhereUniqueWithoutChapterInput = {
  where: Prisma.CqWhereUniqueInput
  update: Prisma.XOR<Prisma.CqUpdateWithoutChapterInput, Prisma.CqUncheckedUpdateWithoutChapterInput>
  create: Prisma.XOR<Prisma.CqCreateWithoutChapterInput, Prisma.CqUncheckedCreateWithoutChapterInput>
}

export type CqUpdateWithWhereUniqueWithoutChapterInput = {
  where: Prisma.CqWhereUniqueInput
  data: Prisma.XOR<Prisma.CqUpdateWithoutChapterInput, Prisma.CqUncheckedUpdateWithoutChapterInput>
}

export type CqUpdateManyWithWhereWithoutChapterInput = {
  where: Prisma.CqScalarWhereInput
  data: Prisma.XOR<Prisma.CqUpdateManyMutationInput, Prisma.CqUncheckedUpdateManyWithoutChapterInput>
}

export type CqCreateWithoutTopicInput = {
  id?: string
  questionA: string
  questionB: string
  questionC: string
  questionD: string
  context?: string | null
  marks?: number
  isActive?: boolean
  createdAt?: Date | string
  updatedAt?: Date | string
  class: Prisma.AcademicClassCreateNestedOneWithoutCqsInput
  subject: Prisma.AcademicSubjectCreateNestedOneWithoutCqsInput
  chapter: Prisma.AcademicChapterCreateNestedOneWithoutCqsInput
  subtopic?: Prisma.AcademicSubTopicCreateNestedOneWithoutCqsInput
}

export type CqUncheckedCreateWithoutTopicInput = {
  id?: string
  questionA: string
  questionB: string
  questionC: string
  questionD: string
  context?: string | null
  marks?: number
  isActive?: boolean
  classId: string
  subjectId: string
  chapterId: string
  subTopicId?: string | null
  createdAt?: Date | string
  updatedAt?: Date | string
}

export type CqCreateOrConnectWithoutTopicInput = {
  where: Prisma.CqWhereUniqueInput
  create: Prisma.XOR<Prisma.CqCreateWithoutTopicInput, Prisma.CqUncheckedCreateWithoutTopicInput>
}

export type CqCreateManyTopicInputEnvelope = {
  data: Prisma.CqCreateManyTopicInput | Prisma.CqCreateManyTopicInput[]
  skipDuplicates?: boolean
}

export type CqUpsertWithWhereUniqueWithoutTopicInput = {
  where: Prisma.CqWhereUniqueInput
  update: Prisma.XOR<Prisma.CqUpdateWithoutTopicInput, Prisma.CqUncheckedUpdateWithoutTopicInput>
  create: Prisma.XOR<Prisma.CqCreateWithoutTopicInput, Prisma.CqUncheckedCreateWithoutTopicInput>
}

export type CqUpdateWithWhereUniqueWithoutTopicInput = {
  where: Prisma.CqWhereUniqueInput
  data: Prisma.XOR<Prisma.CqUpdateWithoutTopicInput, Prisma.CqUncheckedUpdateWithoutTopicInput>
}

export type CqUpdateManyWithWhereWithoutTopicInput = {
  where: Prisma.CqScalarWhereInput
  data: Prisma.XOR<Prisma.CqUpdateManyMutationInput, Prisma.CqUncheckedUpdateManyWithoutTopicInput>
}

export type CqCreateWithoutSubtopicInput = {
  id?: string
  questionA: string
  questionB: string
  questionC: string
  questionD: string
  context?: string | null
  marks?: number
  isActive?: boolean
  createdAt?: Date | string
  updatedAt?: Date | string
  class: Prisma.AcademicClassCreateNestedOneWithoutCqsInput
  subject: Prisma.AcademicSubjectCreateNestedOneWithoutCqsInput
  chapter: Prisma.AcademicChapterCreateNestedOneWithoutCqsInput
  topic?: Prisma.AcademicTopicCreateNestedOneWithoutCqsInput
}

export type CqUncheckedCreateWithoutSubtopicInput = {
  id?: string
  questionA: string
  questionB: string
  questionC: string
  questionD: string
  context?: string | null
  marks?: number
  isActive?: boolean
  classId: string
  subjectId: string
  chapterId: string
  topicId?: string | null
  createdAt?: Date | string
  updatedAt?: Date | string
}

export type CqCreateOrConnectWithoutSubtopicInput = {
  where: Prisma.CqWhereUniqueInput
  create: Prisma.XOR<Prisma.CqCreateWithoutSubtopicInput, Prisma.CqUncheckedCreateWithoutSubtopicInput>
}

export type CqCreateManySubtopicInputEnvelope = {
  data: Prisma.CqCreateManySubtopicInput | Prisma.CqCreateManySubtopicInput[]
  skipDuplicates?: boolean
}

export type CqUpsertWithWhereUniqueWithoutSubtopicInput = {
  where: Prisma.CqWhereUniqueInput
  update: Prisma.XOR<Prisma.CqUpdateWithoutSubtopicInput, Prisma.CqUncheckedUpdateWithoutSubtopicInput>
  create: Prisma.XOR<Prisma.CqCreateWithoutSubtopicInput, Prisma.CqUncheckedCreateWithoutSubtopicInput>
}

export type CqUpdateWithWhereUniqueWithoutSubtopicInput = {
  where: Prisma.CqWhereUniqueInput
  data: Prisma.XOR<Prisma.CqUpdateWithoutSubtopicInput, Prisma.CqUncheckedUpdateWithoutSubtopicInput>
}

export type CqUpdateManyWithWhereWithoutSubtopicInput = {
  where: Prisma.CqScalarWhereInput
  data: Prisma.XOR<Prisma.CqUpdateManyMutationInput, Prisma.CqUncheckedUpdateManyWithoutSubtopicInput>
}

export type CqCreateManyClassInput = {
  id?: string
  questionA: string
  questionB: string
  questionC: string
  questionD: string
  context?: string | null
  marks?: number
  isActive?: boolean
  subjectId: string
  chapterId: string
  topicId?: string | null
  subTopicId?: string | null
  createdAt?: Date | string
  updatedAt?: Date | string
}

export type CqUpdateWithoutClassInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  questionA?: Prisma.StringFieldUpdateOperationsInput | string
  questionB?: Prisma.StringFieldUpdateOperationsInput | string
  questionC?: Prisma.StringFieldUpdateOperationsInput | string
  questionD?: Prisma.StringFieldUpdateOperationsInput | string
  context?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  marks?: Prisma.FloatFieldUpdateOperationsInput | number
  isActive?: Prisma.BoolFieldUpdateOperationsInput | boolean
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  subject?: Prisma.AcademicSubjectUpdateOneRequiredWithoutCqsNestedInput
  chapter?: Prisma.AcademicChapterUpdateOneRequiredWithoutCqsNestedInput
  topic?: Prisma.AcademicTopicUpdateOneWithoutCqsNestedInput
  subtopic?: Prisma.AcademicSubTopicUpdateOneWithoutCqsNestedInput
}

export type CqUncheckedUpdateWithoutClassInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  questionA?: Prisma.StringFieldUpdateOperationsInput | string
  questionB?: Prisma.StringFieldUpdateOperationsInput | string
  questionC?: Prisma.StringFieldUpdateOperationsInput | string
  questionD?: Prisma.StringFieldUpdateOperationsInput | string
  context?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  marks?: Prisma.FloatFieldUpdateOperationsInput | number
  isActive?: Prisma.BoolFieldUpdateOperationsInput | boolean
  subjectId?: Prisma.StringFieldUpdateOperationsInput | string
  chapterId?: Prisma.StringFieldUpdateOperationsInput | string
  topicId?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  subTopicId?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type CqUncheckedUpdateManyWithoutClassInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  questionA?: Prisma.StringFieldUpdateOperationsInput | string
  questionB?: Prisma.StringFieldUpdateOperationsInput | string
  questionC?: Prisma.StringFieldUpdateOperationsInput | string
  questionD?: Prisma.StringFieldUpdateOperationsInput | string
  context?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  marks?: Prisma.FloatFieldUpdateOperationsInput | number
  isActive?: Prisma.BoolFieldUpdateOperationsInput | boolean
  subjectId?: Prisma.StringFieldUpdateOperationsInput | string
  chapterId?: Prisma.StringFieldUpdateOperationsInput | string
  topicId?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  subTopicId?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type CqCreateManySubjectInput = {
  id?: string
  questionA: string
  questionB: string
  questionC: string
  questionD: string
  context?: string | null
  marks?: number
  isActive?: boolean
  classId: string
  chapterId: string
  topicId?: string | null
  subTopicId?: string | null
  createdAt?: Date | string
  updatedAt?: Date | string
}

export type CqUpdateWithoutSubjectInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  questionA?: Prisma.StringFieldUpdateOperationsInput | string
  questionB?: Prisma.StringFieldUpdateOperationsInput | string
  questionC?: Prisma.StringFieldUpdateOperationsInput | string
  questionD?: Prisma.StringFieldUpdateOperationsInput | string
  context?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  marks?: Prisma.FloatFieldUpdateOperationsInput | number
  isActive?: Prisma.BoolFieldUpdateOperationsInput | boolean
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  class?: Prisma.AcademicClassUpdateOneRequiredWithoutCqsNestedInput
  chapter?: Prisma.AcademicChapterUpdateOneRequiredWithoutCqsNestedInput
  topic?: Prisma.AcademicTopicUpdateOneWithoutCqsNestedInput
  subtopic?: Prisma.AcademicSubTopicUpdateOneWithoutCqsNestedInput
}

export type CqUncheckedUpdateWithoutSubjectInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  questionA?: Prisma.StringFieldUpdateOperationsInput | string
  questionB?: Prisma.StringFieldUpdateOperationsInput | string
  questionC?: Prisma.StringFieldUpdateOperationsInput | string
  questionD?: Prisma.StringFieldUpdateOperationsInput | string
  context?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  marks?: Prisma.FloatFieldUpdateOperationsInput | number
  isActive?: Prisma.BoolFieldUpdateOperationsInput | boolean
  classId?: Prisma.StringFieldUpdateOperationsInput | string
  chapterId?: Prisma.StringFieldUpdateOperationsInput | string
  topicId?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  subTopicId?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type CqUncheckedUpdateManyWithoutSubjectInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  questionA?: Prisma.StringFieldUpdateOperationsInput | string
  questionB?: Prisma.StringFieldUpdateOperationsInput | string
  questionC?: Prisma.StringFieldUpdateOperationsInput | string
  questionD?: Prisma.StringFieldUpdateOperationsInput | string
  context?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  marks?: Prisma.FloatFieldUpdateOperationsInput | number
  isActive?: Prisma.BoolFieldUpdateOperationsInput | boolean
  classId?: Prisma.StringFieldUpdateOperationsInput | string
  chapterId?: Prisma.StringFieldUpdateOperationsInput | string
  topicId?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  subTopicId?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type CqCreateManyChapterInput = {
  id?: string
  questionA: string
  questionB: string
  questionC: string
  questionD: string
  context?: string | null
  marks?: number
  isActive?: boolean
  classId: string
  subjectId: string
  topicId?: string | null
  subTopicId?: string | null
  createdAt?: Date | string
  updatedAt?: Date | string
}

export type CqUpdateWithoutChapterInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  questionA?: Prisma.StringFieldUpdateOperationsInput | string
  questionB?: Prisma.StringFieldUpdateOperationsInput | string
  questionC?: Prisma.StringFieldUpdateOperationsInput | string
  questionD?: Prisma.StringFieldUpdateOperationsInput | string
  context?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  marks?: Prisma.FloatFieldUpdateOperationsInput | number
  isActive?: Prisma.BoolFieldUpdateOperationsInput | boolean
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  class?: Prisma.AcademicClassUpdateOneRequiredWithoutCqsNestedInput
  subject?: Prisma.AcademicSubjectUpdateOneRequiredWithoutCqsNestedInput
  topic?: Prisma.AcademicTopicUpdateOneWithoutCqsNestedInput
  subtopic?: Prisma.AcademicSubTopicUpdateOneWithoutCqsNestedInput
}

export type CqUncheckedUpdateWithoutChapterInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  questionA?: Prisma.StringFieldUpdateOperationsInput | string
  questionB?: Prisma.StringFieldUpdateOperationsInput | string
  questionC?: Prisma.StringFieldUpdateOperationsInput | string
  questionD?: Prisma.StringFieldUpdateOperationsInput | string
  context?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  marks?: Prisma.FloatFieldUpdateOperationsInput | number
  isActive?: Prisma.BoolFieldUpdateOperationsInput | boolean
  classId?: Prisma.StringFieldUpdateOperationsInput | string
  subjectId?: Prisma.StringFieldUpdateOperationsInput | string
  topicId?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  subTopicId?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type CqUncheckedUpdateManyWithoutChapterInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  questionA?: Prisma.StringFieldUpdateOperationsInput | string
  questionB?: Prisma.StringFieldUpdateOperationsInput | string
  questionC?: Prisma.StringFieldUpdateOperationsInput | string
  questionD?: Prisma.StringFieldUpdateOperationsInput | string
  context?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  marks?: Prisma.FloatFieldUpdateOperationsInput | number
  isActive?: Prisma.BoolFieldUpdateOperationsInput | boolean
  classId?: Prisma.StringFieldUpdateOperationsInput | string
  subjectId?: Prisma.StringFieldUpdateOperationsInput | string
  topicId?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  subTopicId?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type CqCreateManyTopicInput = {
  id?: string
  questionA: string
  questionB: string
  questionC: string
  questionD: string
  context?: string | null
  marks?: number
  isActive?: boolean
  classId: string
  subjectId: string
  chapterId: string
  subTopicId?: string | null
  createdAt?: Date | string
  updatedAt?: Date | string
}

export type CqUpdateWithoutTopicInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  questionA?: Prisma.StringFieldUpdateOperationsInput | string
  questionB?: Prisma.StringFieldUpdateOperationsInput | string
  questionC?: Prisma.StringFieldUpdateOperationsInput | string
  questionD?: Prisma.StringFieldUpdateOperationsInput | string
  context?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  marks?: Prisma.FloatFieldUpdateOperationsInput | number
  isActive?: Prisma.BoolFieldUpdateOperationsInput | boolean
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  class?: Prisma.AcademicClassUpdateOneRequiredWithoutCqsNestedInput
  subject?: Prisma.AcademicSubjectUpdateOneRequiredWithoutCqsNestedInput
  chapter?: Prisma.AcademicChapterUpdateOneRequiredWithoutCqsNestedInput
  subtopic?: Prisma.AcademicSubTopicUpdateOneWithoutCqsNestedInput
}

export type CqUncheckedUpdateWithoutTopicInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  questionA?: Prisma.StringFieldUpdateOperationsInput | string
  questionB?: Prisma.StringFieldUpdateOperationsInput | string
  questionC?: Prisma.StringFieldUpdateOperationsInput | string
  questionD?: Prisma.StringFieldUpdateOperationsInput | string
  context?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  marks?: Prisma.FloatFieldUpdateOperationsInput | number
  isActive?: Prisma.BoolFieldUpdateOperationsInput | boolean
  classId?: Prisma.StringFieldUpdateOperationsInput | string
  subjectId?: Prisma.StringFieldUpdateOperationsInput | string
  chapterId?: Prisma.StringFieldUpdateOperationsInput | string
  subTopicId?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type CqUncheckedUpdateManyWithoutTopicInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  questionA?: Prisma.StringFieldUpdateOperationsInput | string
  questionB?: Prisma.StringFieldUpdateOperationsInput | string
  questionC?: Prisma.StringFieldUpdateOperationsInput | string
  questionD?: Prisma.StringFieldUpdateOperationsInput | string
  context?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  marks?: Prisma.FloatFieldUpdateOperationsInput | number
  isActive?: Prisma.BoolFieldUpdateOperationsInput | boolean
  classId?: Prisma.StringFieldUpdateOperationsInput | string
  subjectId?: Prisma.StringFieldUpdateOperationsInput | string
  chapterId?: Prisma.StringFieldUpdateOperationsInput | string
  subTopicId?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type CqCreateManySubtopicInput = {
  id?: string
  questionA: string
  questionB: string
  questionC: string
  questionD: string
  context?: string | null
  marks?: number
  isActive?: boolean
  classId: string
  subjectId: string
  chapterId: string
  topicId?: string | null
  createdAt?: Date | string
  updatedAt?: Date | string
}

export type CqUpdateWithoutSubtopicInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  questionA?: Prisma.StringFieldUpdateOperationsInput | string
  questionB?: Prisma.StringFieldUpdateOperationsInput | string
  questionC?: Prisma.StringFieldUpdateOperationsInput | string
  questionD?: Prisma.StringFieldUpdateOperationsInput | string
  context?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  marks?: Prisma.FloatFieldUpdateOperationsInput | number
  isActive?: Prisma.BoolFieldUpdateOperationsInput | boolean
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  class?: Prisma.AcademicClassUpdateOneRequiredWithoutCqsNestedInput
  subject?: Prisma.AcademicSubjectUpdateOneRequiredWithoutCqsNestedInput
  chapter?: Prisma.AcademicChapterUpdateOneRequiredWithoutCqsNestedInput
  topic?: Prisma.AcademicTopicUpdateOneWithoutCqsNestedInput
}

export type CqUncheckedUpdateWithoutSubtopicInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  questionA?: Prisma.StringFieldUpdateOperationsInput | string
  questionB?: Prisma.StringFieldUpdateOperationsInput | string
  questionC?: Prisma.StringFieldUpdateOperationsInput | string
  questionD?: Prisma.StringFieldUpdateOperationsInput | string
  context?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  marks?: Prisma.FloatFieldUpdateOperationsInput | number
  isActive?: Prisma.BoolFieldUpdateOperationsInput | boolean
  classId?: Prisma.StringFieldUpdateOperationsInput | string
  subjectId?: Prisma.StringFieldUpdateOperationsInput | string
  chapterId?: Prisma.StringFieldUpdateOperationsInput | string
  topicId?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type CqUncheckedUpdateManyWithoutSubtopicInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  questionA?: Prisma.StringFieldUpdateOperationsInput | string
  questionB?: Prisma.StringFieldUpdateOperationsInput | string
  questionC?: Prisma.StringFieldUpdateOperationsInput | string
  questionD?: Prisma.StringFieldUpdateOperationsInput | string
  context?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  marks?: Prisma.FloatFieldUpdateOperationsInput | number
  isActive?: Prisma.BoolFieldUpdateOperationsInput | boolean
  classId?: Prisma.StringFieldUpdateOperationsInput | string
  subjectId?: Prisma.StringFieldUpdateOperationsInput | string
  chapterId?: Prisma.StringFieldUpdateOperationsInput | string
  topicId?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}



export type CqSelect<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  questionA?: boolean
  questionB?: boolean
  questionC?: boolean
  questionD?: boolean
  context?: boolean
  marks?: boolean
  isActive?: boolean
  classId?: boolean
  subjectId?: boolean
  chapterId?: boolean
  topicId?: boolean
  subTopicId?: boolean
  createdAt?: boolean
  updatedAt?: boolean
  class?: boolean | Prisma.AcademicClassDefaultArgs<ExtArgs>
  subject?: boolean | Prisma.AcademicSubjectDefaultArgs<ExtArgs>
  chapter?: boolean | Prisma.AcademicChapterDefaultArgs<ExtArgs>
  topic?: boolean | Prisma.Cq$topicArgs<ExtArgs>
  subtopic?: boolean | Prisma.Cq$subtopicArgs<ExtArgs>
}, ExtArgs["result"]["cq"]>

export type CqSelectCreateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  questionA?: boolean
  questionB?: boolean
  questionC?: boolean
  questionD?: boolean
  context?: boolean
  marks?: boolean
  isActive?: boolean
  classId?: boolean
  subjectId?: boolean
  chapterId?: boolean
  topicId?: boolean
  subTopicId?: boolean
  createdAt?: boolean
  updatedAt?: boolean
  class?: boolean | Prisma.AcademicClassDefaultArgs<ExtArgs>
  subject?: boolean | Prisma.AcademicSubjectDefaultArgs<ExtArgs>
  chapter?: boolean | Prisma.AcademicChapterDefaultArgs<ExtArgs>
  topic?: boolean | Prisma.Cq$topicArgs<ExtArgs>
  subtopic?: boolean | Prisma.Cq$subtopicArgs<ExtArgs>
}, ExtArgs["result"]["cq"]>

export type CqSelectUpdateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  questionA?: boolean
  questionB?: boolean
  questionC?: boolean
  questionD?: boolean
  context?: boolean
  marks?: boolean
  isActive?: boolean
  classId?: boolean
  subjectId?: boolean
  chapterId?: boolean
  topicId?: boolean
  subTopicId?: boolean
  createdAt?: boolean
  updatedAt?: boolean
  class?: boolean | Prisma.AcademicClassDefaultArgs<ExtArgs>
  subject?: boolean | Prisma.AcademicSubjectDefaultArgs<ExtArgs>
  chapter?: boolean | Prisma.AcademicChapterDefaultArgs<ExtArgs>
  topic?: boolean | Prisma.Cq$topicArgs<ExtArgs>
  subtopic?: boolean | Prisma.Cq$subtopicArgs<ExtArgs>
}, ExtArgs["result"]["cq"]>

export type CqSelectScalar = {
  id?: boolean
  questionA?: boolean
  questionB?: boolean
  questionC?: boolean
  questionD?: boolean
  context?: boolean
  marks?: boolean
  isActive?: boolean
  classId?: boolean
  subjectId?: boolean
  chapterId?: boolean
  topicId?: boolean
  subTopicId?: boolean
  createdAt?: boolean
  updatedAt?: boolean
}

export type CqOmit<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetOmit<"id" | "questionA" | "questionB" | "questionC" | "questionD" | "context" | "marks" | "isActive" | "classId" | "subjectId" | "chapterId" | "topicId" | "subTopicId" | "createdAt" | "updatedAt", ExtArgs["result"]["cq"]>
export type CqInclude<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  class?: boolean | Prisma.AcademicClassDefaultArgs<ExtArgs>
  subject?: boolean | Prisma.AcademicSubjectDefaultArgs<ExtArgs>
  chapter?: boolean | Prisma.AcademicChapterDefaultArgs<ExtArgs>
  topic?: boolean | Prisma.Cq$topicArgs<ExtArgs>
  subtopic?: boolean | Prisma.Cq$subtopicArgs<ExtArgs>
}
export type CqIncludeCreateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  class?: boolean | Prisma.AcademicClassDefaultArgs<ExtArgs>
  subject?: boolean | Prisma.AcademicSubjectDefaultArgs<ExtArgs>
  chapter?: boolean | Prisma.AcademicChapterDefaultArgs<ExtArgs>
  topic?: boolean | Prisma.Cq$topicArgs<ExtArgs>
  subtopic?: boolean | Prisma.Cq$subtopicArgs<ExtArgs>
}
export type CqIncludeUpdateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  class?: boolean | Prisma.AcademicClassDefaultArgs<ExtArgs>
  subject?: boolean | Prisma.AcademicSubjectDefaultArgs<ExtArgs>
  chapter?: boolean | Prisma.AcademicChapterDefaultArgs<ExtArgs>
  topic?: boolean | Prisma.Cq$topicArgs<ExtArgs>
  subtopic?: boolean | Prisma.Cq$subtopicArgs<ExtArgs>
}

export type $CqPayload<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  name: "Cq"
  objects: {
    class: Prisma.$AcademicClassPayload<ExtArgs>
    subject: Prisma.$AcademicSubjectPayload<ExtArgs>
    chapter: Prisma.$AcademicChapterPayload<ExtArgs>
    topic: Prisma.$AcademicTopicPayload<ExtArgs> | null
    subtopic: Prisma.$AcademicSubTopicPayload<ExtArgs> | null
  }
  scalars: runtime.Types.Extensions.GetPayloadResult<{
    id: string
    questionA: string
    questionB: string
    questionC: string
    questionD: string
    context: string | null
    marks: number
    isActive: boolean
    classId: string
    subjectId: string
    chapterId: string
    topicId: string | null
    subTopicId: string | null
    createdAt: Date
    updatedAt: Date
  }, ExtArgs["result"]["cq"]>
  composites: {}
}

export type CqGetPayload<S extends boolean | null | undefined | CqDefaultArgs> = runtime.Types.Result.GetResult<Prisma.$CqPayload, S>

export type CqCountArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> =
  Omit<CqFindManyArgs, 'select' | 'include' | 'distinct' | 'omit'> & {
    select?: CqCountAggregateInputType | true
  }

export interface CqDelegate<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs, GlobalOmitOptions = {}> {
  [K: symbol]: { types: Prisma.TypeMap<ExtArgs>['model']['Cq'], meta: { name: 'Cq' } }
  /**
   * Find zero or one Cq that matches the filter.
   * @param {CqFindUniqueArgs} args - Arguments to find a Cq
   * @example
   * // Get one Cq
   * const cq = await prisma.cq.findUnique({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findUnique<T extends CqFindUniqueArgs>(args: Prisma.SelectSubset<T, CqFindUniqueArgs<ExtArgs>>): Prisma.Prisma__CqClient<runtime.Types.Result.GetResult<Prisma.$CqPayload<ExtArgs>, T, "findUnique", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>

  /**
   * Find one Cq that matches the filter or throw an error with `error.code='P2025'`
   * if no matches were found.
   * @param {CqFindUniqueOrThrowArgs} args - Arguments to find a Cq
   * @example
   * // Get one Cq
   * const cq = await prisma.cq.findUniqueOrThrow({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findUniqueOrThrow<T extends CqFindUniqueOrThrowArgs>(args: Prisma.SelectSubset<T, CqFindUniqueOrThrowArgs<ExtArgs>>): Prisma.Prisma__CqClient<runtime.Types.Result.GetResult<Prisma.$CqPayload<ExtArgs>, T, "findUniqueOrThrow", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Find the first Cq that matches the filter.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {CqFindFirstArgs} args - Arguments to find a Cq
   * @example
   * // Get one Cq
   * const cq = await prisma.cq.findFirst({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findFirst<T extends CqFindFirstArgs>(args?: Prisma.SelectSubset<T, CqFindFirstArgs<ExtArgs>>): Prisma.Prisma__CqClient<runtime.Types.Result.GetResult<Prisma.$CqPayload<ExtArgs>, T, "findFirst", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>

  /**
   * Find the first Cq that matches the filter or
   * throw `PrismaKnownClientError` with `P2025` code if no matches were found.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {CqFindFirstOrThrowArgs} args - Arguments to find a Cq
   * @example
   * // Get one Cq
   * const cq = await prisma.cq.findFirstOrThrow({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findFirstOrThrow<T extends CqFindFirstOrThrowArgs>(args?: Prisma.SelectSubset<T, CqFindFirstOrThrowArgs<ExtArgs>>): Prisma.Prisma__CqClient<runtime.Types.Result.GetResult<Prisma.$CqPayload<ExtArgs>, T, "findFirstOrThrow", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Find zero or more Cqs that matches the filter.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {CqFindManyArgs} args - Arguments to filter and select certain fields only.
   * @example
   * // Get all Cqs
   * const cqs = await prisma.cq.findMany()
   * 
   * // Get first 10 Cqs
   * const cqs = await prisma.cq.findMany({ take: 10 })
   * 
   * // Only select the `id`
   * const cqWithIdOnly = await prisma.cq.findMany({ select: { id: true } })
   * 
   */
  findMany<T extends CqFindManyArgs>(args?: Prisma.SelectSubset<T, CqFindManyArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$CqPayload<ExtArgs>, T, "findMany", GlobalOmitOptions>>

  /**
   * Create a Cq.
   * @param {CqCreateArgs} args - Arguments to create a Cq.
   * @example
   * // Create one Cq
   * const Cq = await prisma.cq.create({
   *   data: {
   *     // ... data to create a Cq
   *   }
   * })
   * 
   */
  create<T extends CqCreateArgs>(args: Prisma.SelectSubset<T, CqCreateArgs<ExtArgs>>): Prisma.Prisma__CqClient<runtime.Types.Result.GetResult<Prisma.$CqPayload<ExtArgs>, T, "create", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Create many Cqs.
   * @param {CqCreateManyArgs} args - Arguments to create many Cqs.
   * @example
   * // Create many Cqs
   * const cq = await prisma.cq.createMany({
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   *     
   */
  createMany<T extends CqCreateManyArgs>(args?: Prisma.SelectSubset<T, CqCreateManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Create many Cqs and returns the data saved in the database.
   * @param {CqCreateManyAndReturnArgs} args - Arguments to create many Cqs.
   * @example
   * // Create many Cqs
   * const cq = await prisma.cq.createManyAndReturn({
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * 
   * // Create many Cqs and only return the `id`
   * const cqWithIdOnly = await prisma.cq.createManyAndReturn({
   *   select: { id: true },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * 
   */
  createManyAndReturn<T extends CqCreateManyAndReturnArgs>(args?: Prisma.SelectSubset<T, CqCreateManyAndReturnArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$CqPayload<ExtArgs>, T, "createManyAndReturn", GlobalOmitOptions>>

  /**
   * Delete a Cq.
   * @param {CqDeleteArgs} args - Arguments to delete one Cq.
   * @example
   * // Delete one Cq
   * const Cq = await prisma.cq.delete({
   *   where: {
   *     // ... filter to delete one Cq
   *   }
   * })
   * 
   */
  delete<T extends CqDeleteArgs>(args: Prisma.SelectSubset<T, CqDeleteArgs<ExtArgs>>): Prisma.Prisma__CqClient<runtime.Types.Result.GetResult<Prisma.$CqPayload<ExtArgs>, T, "delete", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Update one Cq.
   * @param {CqUpdateArgs} args - Arguments to update one Cq.
   * @example
   * // Update one Cq
   * const cq = await prisma.cq.update({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: {
   *     // ... provide data here
   *   }
   * })
   * 
   */
  update<T extends CqUpdateArgs>(args: Prisma.SelectSubset<T, CqUpdateArgs<ExtArgs>>): Prisma.Prisma__CqClient<runtime.Types.Result.GetResult<Prisma.$CqPayload<ExtArgs>, T, "update", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Delete zero or more Cqs.
   * @param {CqDeleteManyArgs} args - Arguments to filter Cqs to delete.
   * @example
   * // Delete a few Cqs
   * const { count } = await prisma.cq.deleteMany({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   * 
   */
  deleteMany<T extends CqDeleteManyArgs>(args?: Prisma.SelectSubset<T, CqDeleteManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Update zero or more Cqs.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {CqUpdateManyArgs} args - Arguments to update one or more rows.
   * @example
   * // Update many Cqs
   * const cq = await prisma.cq.updateMany({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: {
   *     // ... provide data here
   *   }
   * })
   * 
   */
  updateMany<T extends CqUpdateManyArgs>(args: Prisma.SelectSubset<T, CqUpdateManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Update zero or more Cqs and returns the data updated in the database.
   * @param {CqUpdateManyAndReturnArgs} args - Arguments to update many Cqs.
   * @example
   * // Update many Cqs
   * const cq = await prisma.cq.updateManyAndReturn({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * 
   * // Update zero or more Cqs and only return the `id`
   * const cqWithIdOnly = await prisma.cq.updateManyAndReturn({
   *   select: { id: true },
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * 
   */
  updateManyAndReturn<T extends CqUpdateManyAndReturnArgs>(args: Prisma.SelectSubset<T, CqUpdateManyAndReturnArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$CqPayload<ExtArgs>, T, "updateManyAndReturn", GlobalOmitOptions>>

  /**
   * Create or update one Cq.
   * @param {CqUpsertArgs} args - Arguments to update or create a Cq.
   * @example
   * // Update or create a Cq
   * const cq = await prisma.cq.upsert({
   *   create: {
   *     // ... data to create a Cq
   *   },
   *   update: {
   *     // ... in case it already exists, update
   *   },
   *   where: {
   *     // ... the filter for the Cq we want to update
   *   }
   * })
   */
  upsert<T extends CqUpsertArgs>(args: Prisma.SelectSubset<T, CqUpsertArgs<ExtArgs>>): Prisma.Prisma__CqClient<runtime.Types.Result.GetResult<Prisma.$CqPayload<ExtArgs>, T, "upsert", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>


  /**
   * Count the number of Cqs.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {CqCountArgs} args - Arguments to filter Cqs to count.
   * @example
   * // Count the number of Cqs
   * const count = await prisma.cq.count({
   *   where: {
   *     // ... the filter for the Cqs we want to count
   *   }
   * })
  **/
  count<T extends CqCountArgs>(
    args?: Prisma.Subset<T, CqCountArgs>,
  ): Prisma.PrismaPromise<
    T extends runtime.Types.Utils.Record<'select', any>
      ? T['select'] extends true
        ? number
        : Prisma.GetScalarType<T['select'], CqCountAggregateOutputType>
      : number
  >

  /**
   * Allows you to perform aggregations operations on a Cq.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {CqAggregateArgs} args - Select which aggregations you would like to apply and on what fields.
   * @example
   * // Ordered by age ascending
   * // Where email contains prisma.io
   * // Limited to the 10 users
   * const aggregations = await prisma.user.aggregate({
   *   _avg: {
   *     age: true,
   *   },
   *   where: {
   *     email: {
   *       contains: "prisma.io",
   *     },
   *   },
   *   orderBy: {
   *     age: "asc",
   *   },
   *   take: 10,
   * })
  **/
  aggregate<T extends CqAggregateArgs>(args: Prisma.Subset<T, CqAggregateArgs>): Prisma.PrismaPromise<GetCqAggregateType<T>>

  /**
   * Group by Cq.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {CqGroupByArgs} args - Group by arguments.
   * @example
   * // Group by city, order by createdAt, get count
   * const result = await prisma.user.groupBy({
   *   by: ['city', 'createdAt'],
   *   orderBy: {
   *     createdAt: true
   *   },
   *   _count: {
   *     _all: true
   *   },
   * })
   * 
  **/
  groupBy<
    T extends CqGroupByArgs,
    HasSelectOrTake extends Prisma.Or<
      Prisma.Extends<'skip', Prisma.Keys<T>>,
      Prisma.Extends<'take', Prisma.Keys<T>>
    >,
    OrderByArg extends Prisma.True extends HasSelectOrTake
      ? { orderBy: CqGroupByArgs['orderBy'] }
      : { orderBy?: CqGroupByArgs['orderBy'] },
    OrderFields extends Prisma.ExcludeUnderscoreKeys<Prisma.Keys<Prisma.MaybeTupleToUnion<T['orderBy']>>>,
    ByFields extends Prisma.MaybeTupleToUnion<T['by']>,
    ByValid extends Prisma.Has<ByFields, OrderFields>,
    HavingFields extends Prisma.GetHavingFields<T['having']>,
    HavingValid extends Prisma.Has<ByFields, HavingFields>,
    ByEmpty extends T['by'] extends never[] ? Prisma.True : Prisma.False,
    InputErrors extends ByEmpty extends Prisma.True
    ? `Error: "by" must not be empty.`
    : HavingValid extends Prisma.False
    ? {
        [P in HavingFields]: P extends ByFields
          ? never
          : P extends string
          ? `Error: Field "${P}" used in "having" needs to be provided in "by".`
          : [
              Error,
              'Field ',
              P,
              ` in "having" needs to be provided in "by"`,
            ]
      }[HavingFields]
    : 'take' extends Prisma.Keys<T>
    ? 'orderBy' extends Prisma.Keys<T>
      ? ByValid extends Prisma.True
        ? {}
        : {
            [P in OrderFields]: P extends ByFields
              ? never
              : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
          }[OrderFields]
      : 'Error: If you provide "take", you also need to provide "orderBy"'
    : 'skip' extends Prisma.Keys<T>
    ? 'orderBy' extends Prisma.Keys<T>
      ? ByValid extends Prisma.True
        ? {}
        : {
            [P in OrderFields]: P extends ByFields
              ? never
              : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
          }[OrderFields]
      : 'Error: If you provide "skip", you also need to provide "orderBy"'
    : ByValid extends Prisma.True
    ? {}
    : {
        [P in OrderFields]: P extends ByFields
          ? never
          : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
      }[OrderFields]
  >(args: Prisma.SubsetIntersection<T, CqGroupByArgs, OrderByArg> & InputErrors): {} extends InputErrors ? GetCqGroupByPayload<T> : Prisma.PrismaPromise<InputErrors>
/**
 * Fields of the Cq model
 */
readonly fields: CqFieldRefs;
}

/**
 * The delegate class that acts as a "Promise-like" for Cq.
 * Why is this prefixed with `Prisma__`?
 * Because we want to prevent naming conflicts as mentioned in
 * https://github.com/prisma/prisma-client-js/issues/707
 */
export interface Prisma__CqClient<T, Null = never, ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs, GlobalOmitOptions = {}> extends Prisma.PrismaPromise<T> {
  readonly [Symbol.toStringTag]: "PrismaPromise"
  class<T extends Prisma.AcademicClassDefaultArgs<ExtArgs> = {}>(args?: Prisma.Subset<T, Prisma.AcademicClassDefaultArgs<ExtArgs>>): Prisma.Prisma__AcademicClassClient<runtime.Types.Result.GetResult<Prisma.$AcademicClassPayload<ExtArgs>, T, "findUniqueOrThrow", GlobalOmitOptions> | Null, Null, ExtArgs, GlobalOmitOptions>
  subject<T extends Prisma.AcademicSubjectDefaultArgs<ExtArgs> = {}>(args?: Prisma.Subset<T, Prisma.AcademicSubjectDefaultArgs<ExtArgs>>): Prisma.Prisma__AcademicSubjectClient<runtime.Types.Result.GetResult<Prisma.$AcademicSubjectPayload<ExtArgs>, T, "findUniqueOrThrow", GlobalOmitOptions> | Null, Null, ExtArgs, GlobalOmitOptions>
  chapter<T extends Prisma.AcademicChapterDefaultArgs<ExtArgs> = {}>(args?: Prisma.Subset<T, Prisma.AcademicChapterDefaultArgs<ExtArgs>>): Prisma.Prisma__AcademicChapterClient<runtime.Types.Result.GetResult<Prisma.$AcademicChapterPayload<ExtArgs>, T, "findUniqueOrThrow", GlobalOmitOptions> | Null, Null, ExtArgs, GlobalOmitOptions>
  topic<T extends Prisma.Cq$topicArgs<ExtArgs> = {}>(args?: Prisma.Subset<T, Prisma.Cq$topicArgs<ExtArgs>>): Prisma.Prisma__AcademicTopicClient<runtime.Types.Result.GetResult<Prisma.$AcademicTopicPayload<ExtArgs>, T, "findUniqueOrThrow", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>
  subtopic<T extends Prisma.Cq$subtopicArgs<ExtArgs> = {}>(args?: Prisma.Subset<T, Prisma.Cq$subtopicArgs<ExtArgs>>): Prisma.Prisma__AcademicSubTopicClient<runtime.Types.Result.GetResult<Prisma.$AcademicSubTopicPayload<ExtArgs>, T, "findUniqueOrThrow", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>
  /**
   * Attaches callbacks for the resolution and/or rejection of the Promise.
   * @param onfulfilled The callback to execute when the Promise is resolved.
   * @param onrejected The callback to execute when the Promise is rejected.
   * @returns A Promise for the completion of which ever callback is executed.
   */
  then<TResult1 = T, TResult2 = never>(onfulfilled?: ((value: T) => TResult1 | PromiseLike<TResult1>) | undefined | null, onrejected?: ((reason: any) => TResult2 | PromiseLike<TResult2>) | undefined | null): runtime.Types.Utils.JsPromise<TResult1 | TResult2>
  /**
   * Attaches a callback for only the rejection of the Promise.
   * @param onrejected The callback to execute when the Promise is rejected.
   * @returns A Promise for the completion of the callback.
   */
  catch<TResult = never>(onrejected?: ((reason: any) => TResult | PromiseLike<TResult>) | undefined | null): runtime.Types.Utils.JsPromise<T | TResult>
  /**
   * Attaches a callback that is invoked when the Promise is settled (fulfilled or rejected). The
   * resolved value cannot be modified from the callback.
   * @param onfinally The callback to execute when the Promise is settled (fulfilled or rejected).
   * @returns A Promise for the completion of the callback.
   */
  finally(onfinally?: (() => void) | undefined | null): runtime.Types.Utils.JsPromise<T>
}




/**
 * Fields of the Cq model
 */
export interface CqFieldRefs {
  readonly id: Prisma.FieldRef<"Cq", 'String'>
  readonly questionA: Prisma.FieldRef<"Cq", 'String'>
  readonly questionB: Prisma.FieldRef<"Cq", 'String'>
  readonly questionC: Prisma.FieldRef<"Cq", 'String'>
  readonly questionD: Prisma.FieldRef<"Cq", 'String'>
  readonly context: Prisma.FieldRef<"Cq", 'String'>
  readonly marks: Prisma.FieldRef<"Cq", 'Float'>
  readonly isActive: Prisma.FieldRef<"Cq", 'Boolean'>
  readonly classId: Prisma.FieldRef<"Cq", 'String'>
  readonly subjectId: Prisma.FieldRef<"Cq", 'String'>
  readonly chapterId: Prisma.FieldRef<"Cq", 'String'>
  readonly topicId: Prisma.FieldRef<"Cq", 'String'>
  readonly subTopicId: Prisma.FieldRef<"Cq", 'String'>
  readonly createdAt: Prisma.FieldRef<"Cq", 'DateTime'>
  readonly updatedAt: Prisma.FieldRef<"Cq", 'DateTime'>
}
    

// Custom InputTypes
/**
 * Cq findUnique
 */
export type CqFindUniqueArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Cq
   */
  select?: Prisma.CqSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Cq
   */
  omit?: Prisma.CqOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.CqInclude<ExtArgs> | null
  /**
   * Filter, which Cq to fetch.
   */
  where: Prisma.CqWhereUniqueInput
}

/**
 * Cq findUniqueOrThrow
 */
export type CqFindUniqueOrThrowArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Cq
   */
  select?: Prisma.CqSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Cq
   */
  omit?: Prisma.CqOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.CqInclude<ExtArgs> | null
  /**
   * Filter, which Cq to fetch.
   */
  where: Prisma.CqWhereUniqueInput
}

/**
 * Cq findFirst
 */
export type CqFindFirstArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Cq
   */
  select?: Prisma.CqSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Cq
   */
  omit?: Prisma.CqOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.CqInclude<ExtArgs> | null
  /**
   * Filter, which Cq to fetch.
   */
  where?: Prisma.CqWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of Cqs to fetch.
   */
  orderBy?: Prisma.CqOrderByWithRelationInput | Prisma.CqOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for searching for Cqs.
   */
  cursor?: Prisma.CqWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` Cqs from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` Cqs.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of Cqs.
   */
  distinct?: Prisma.CqScalarFieldEnum | Prisma.CqScalarFieldEnum[]
}

/**
 * Cq findFirstOrThrow
 */
export type CqFindFirstOrThrowArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Cq
   */
  select?: Prisma.CqSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Cq
   */
  omit?: Prisma.CqOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.CqInclude<ExtArgs> | null
  /**
   * Filter, which Cq to fetch.
   */
  where?: Prisma.CqWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of Cqs to fetch.
   */
  orderBy?: Prisma.CqOrderByWithRelationInput | Prisma.CqOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for searching for Cqs.
   */
  cursor?: Prisma.CqWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` Cqs from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` Cqs.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of Cqs.
   */
  distinct?: Prisma.CqScalarFieldEnum | Prisma.CqScalarFieldEnum[]
}

/**
 * Cq findMany
 */
export type CqFindManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Cq
   */
  select?: Prisma.CqSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Cq
   */
  omit?: Prisma.CqOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.CqInclude<ExtArgs> | null
  /**
   * Filter, which Cqs to fetch.
   */
  where?: Prisma.CqWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of Cqs to fetch.
   */
  orderBy?: Prisma.CqOrderByWithRelationInput | Prisma.CqOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for listing Cqs.
   */
  cursor?: Prisma.CqWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` Cqs from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` Cqs.
   */
  skip?: number
  distinct?: Prisma.CqScalarFieldEnum | Prisma.CqScalarFieldEnum[]
}

/**
 * Cq create
 */
export type CqCreateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Cq
   */
  select?: Prisma.CqSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Cq
   */
  omit?: Prisma.CqOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.CqInclude<ExtArgs> | null
  /**
   * The data needed to create a Cq.
   */
  data: Prisma.XOR<Prisma.CqCreateInput, Prisma.CqUncheckedCreateInput>
}

/**
 * Cq createMany
 */
export type CqCreateManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * The data used to create many Cqs.
   */
  data: Prisma.CqCreateManyInput | Prisma.CqCreateManyInput[]
  skipDuplicates?: boolean
}

/**
 * Cq createManyAndReturn
 */
export type CqCreateManyAndReturnArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Cq
   */
  select?: Prisma.CqSelectCreateManyAndReturn<ExtArgs> | null
  /**
   * Omit specific fields from the Cq
   */
  omit?: Prisma.CqOmit<ExtArgs> | null
  /**
   * The data used to create many Cqs.
   */
  data: Prisma.CqCreateManyInput | Prisma.CqCreateManyInput[]
  skipDuplicates?: boolean
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.CqIncludeCreateManyAndReturn<ExtArgs> | null
}

/**
 * Cq update
 */
export type CqUpdateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Cq
   */
  select?: Prisma.CqSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Cq
   */
  omit?: Prisma.CqOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.CqInclude<ExtArgs> | null
  /**
   * The data needed to update a Cq.
   */
  data: Prisma.XOR<Prisma.CqUpdateInput, Prisma.CqUncheckedUpdateInput>
  /**
   * Choose, which Cq to update.
   */
  where: Prisma.CqWhereUniqueInput
}

/**
 * Cq updateMany
 */
export type CqUpdateManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * The data used to update Cqs.
   */
  data: Prisma.XOR<Prisma.CqUpdateManyMutationInput, Prisma.CqUncheckedUpdateManyInput>
  /**
   * Filter which Cqs to update
   */
  where?: Prisma.CqWhereInput
  /**
   * Limit how many Cqs to update.
   */
  limit?: number
}

/**
 * Cq updateManyAndReturn
 */
export type CqUpdateManyAndReturnArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Cq
   */
  select?: Prisma.CqSelectUpdateManyAndReturn<ExtArgs> | null
  /**
   * Omit specific fields from the Cq
   */
  omit?: Prisma.CqOmit<ExtArgs> | null
  /**
   * The data used to update Cqs.
   */
  data: Prisma.XOR<Prisma.CqUpdateManyMutationInput, Prisma.CqUncheckedUpdateManyInput>
  /**
   * Filter which Cqs to update
   */
  where?: Prisma.CqWhereInput
  /**
   * Limit how many Cqs to update.
   */
  limit?: number
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.CqIncludeUpdateManyAndReturn<ExtArgs> | null
}

/**
 * Cq upsert
 */
export type CqUpsertArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Cq
   */
  select?: Prisma.CqSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Cq
   */
  omit?: Prisma.CqOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.CqInclude<ExtArgs> | null
  /**
   * The filter to search for the Cq to update in case it exists.
   */
  where: Prisma.CqWhereUniqueInput
  /**
   * In case the Cq found by the `where` argument doesn't exist, create a new Cq with this data.
   */
  create: Prisma.XOR<Prisma.CqCreateInput, Prisma.CqUncheckedCreateInput>
  /**
   * In case the Cq was found with the provided `where` argument, update it with this data.
   */
  update: Prisma.XOR<Prisma.CqUpdateInput, Prisma.CqUncheckedUpdateInput>
}

/**
 * Cq delete
 */
export type CqDeleteArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Cq
   */
  select?: Prisma.CqSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Cq
   */
  omit?: Prisma.CqOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.CqInclude<ExtArgs> | null
  /**
   * Filter which Cq to delete.
   */
  where: Prisma.CqWhereUniqueInput
}

/**
 * Cq deleteMany
 */
export type CqDeleteManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Filter which Cqs to delete
   */
  where?: Prisma.CqWhereInput
  /**
   * Limit how many Cqs to delete.
   */
  limit?: number
}

/**
 * Cq.topic
 */
export type Cq$topicArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the AcademicTopic
   */
  select?: Prisma.AcademicTopicSelect<ExtArgs> | null
  /**
   * Omit specific fields from the AcademicTopic
   */
  omit?: Prisma.AcademicTopicOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.AcademicTopicInclude<ExtArgs> | null
  where?: Prisma.AcademicTopicWhereInput
}

/**
 * Cq.subtopic
 */
export type Cq$subtopicArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the AcademicSubTopic
   */
  select?: Prisma.AcademicSubTopicSelect<ExtArgs> | null
  /**
   * Omit specific fields from the AcademicSubTopic
   */
  omit?: Prisma.AcademicSubTopicOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.AcademicSubTopicInclude<ExtArgs> | null
  where?: Prisma.AcademicSubTopicWhereInput
}

/**
 * Cq without action
 */
export type CqDefaultArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Cq
   */
  select?: Prisma.CqSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Cq
   */
  omit?: Prisma.CqOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.CqInclude<ExtArgs> | null
}
